/*****************************************************************
 * Copyright (c) 2010 Texas Instruments and others
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Patrick Chuong (Texas Instruments) - Pin and Clone Supports (331781)
 *     Patrick Chuong (Texas Instruments) - Add support for icon overlay in the debug view (Bug 334566)
 *****************************************************************/
package org.eclipse.cdt.debug.ui; 

import org.eclipse.jface.resource.ImageDescriptor;
import org.eclipse.ui.IWorkbenchPart;

/**
 * Debug element that wants to enable pin capability should be adaptable to this interface.
 * If the debug element is not adaptable to this interface, than the default implementation
 * will be provided.
 * <br><br>
 * When user press the 'Pin' action in a view that supports debug context pinning, the 
 * DebugEventFilterService calls the <code>pin</code> method with the selected debug context.
 * If more than one debug context is selected, than <code>pin</code> is called multiple times.
 * The <code>pin</code> method should returns a handle for the pinned debug context and when
 * there is a debug context change event generated by the debug context manager, 
 * <code>isPinnedTo</code> will be call by the DebugEventFilterService to determine whether the
 * debug context in question is pinned to the handle returned by the <code>pin</code> method.
 * 
 *  @since 7.1
 */
public interface IPinProvider {
	/**
	 * Pin element color descriptor.
	 */
	public interface IPinElementColorDescriptor {
		/**
		 * Default number of color count.
		 */
		final int DEFAULT_COLOR_COUNT = 3; 
		
		/**
		 * An undefined color
		 */
		int UNDEFINED = -1;
		
		/**
		 * Green color (Default)
		 */
		int GREEN = 0;
		
		/**
		 * Red color
		 */
		int RED = 1;
		
		/**
		 * Blue color
		 */
		int BLUE = 2;
		
		/**
		 * Returns the overlay pin color. The overlay pin will be used to decorate the debug view for element that
		 * is pinned to a view.
		 * 
		 * @return one of the overlay color
		 */
		int getOverlayColor();
		
		/**
		 * Returns the toolbar pin action image description to use when the view is pinned, can be <code>null</code>. 
		 * If <code>null</code>, than the default image description will be use.
		 *  
		 * @return the icon descriptor
		 */
		ImageDescriptor getToolbarIconDescriptor();
	}
	
	/**
	 * Pin element handler interface. 
	 */
	public interface IPinElementHandle {
		/**
		 * Returns the debug context for this handle.
		 * 
		 * @return the debug context
		 */
		Object getDebugContext();
		
		/**
		 * Returns the label the label will be used to display
		 * in the pinned view's descriptor.
		 *  
		 * @return the handle label
		 */
		String getLabel();
		
		/**
		 * Returns color descriptor for this element.
		 * 
		 * @return the color descriptor, can be <code>null</code>
		 */
		IPinElementColorDescriptor getPinElementColorDescriptor();
	}
	
	/**
	 * Returns whether the debug context is pinnable.
	 * 
	 * @param part the workbench part
	 * @param debugContext the debug context in question
	 * @return true if the debug context is pinnable
	 */
	boolean isPinnable(IWorkbenchPart part, Object debugContext);
	
	/**
	 * Pin the debug context and returns a handle for the pinned debug context.
	 * 
	 * @param part the workbench part
	 * @param debugContext the debug context to pin to
	 * @return a handle for the pinned debug context
	 */

	IPinElementHandle pin(IWorkbenchPart part, Object debugContext);
	
	/**
	 * Unpin the debug context for the given pin handle.
	 *  
	 * @param part the workbench part
	 * @param handle the handle for the pinned debug context
	 */
	void unpin(IWorkbenchPart part, IPinElementHandle handle);
	
	
	/**
	 * Returns true if the debug context belongs to the handle. If returning true,
	 * than the debug context change event will be delegate to the view. 
	 * 
	 * @param debugContext the debug context in question
	 * @param handle an existing pinned debug context handle
	 * @return true to delegate debug context change event to the view
	 */
	boolean isPinnedTo(Object debugContext, IPinElementHandle handle);
}
