/*******************************************************************************
 * Copyright (c) 2008 Radoslav Gerganov
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Radoslav Gerganov - initial API and implementation
 *******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_eclipse_tm_rapi_Rapi */

#ifndef _Included_org_eclipse_tm_rapi_Rapi
#define _Included_org_eclipse_tm_rapi_Rapi
#ifdef __cplusplus
extern "C" {
#endif
#undef org_eclipse_tm_rapi_Rapi_NOERROR
#define org_eclipse_tm_rapi_Rapi_NOERROR 0L
#undef org_eclipse_tm_rapi_Rapi_GENERIC_READ
#define org_eclipse_tm_rapi_Rapi_GENERIC_READ -2147483648L
#undef org_eclipse_tm_rapi_Rapi_GENERIC_WRITE
#define org_eclipse_tm_rapi_Rapi_GENERIC_WRITE 1073741824L
#undef org_eclipse_tm_rapi_Rapi_FILE_SHARE_READ
#define org_eclipse_tm_rapi_Rapi_FILE_SHARE_READ 1L
#undef org_eclipse_tm_rapi_Rapi_FILE_SHARE_WRITE
#define org_eclipse_tm_rapi_Rapi_FILE_SHARE_WRITE 2L
#undef org_eclipse_tm_rapi_Rapi_CREATE_NEW
#define org_eclipse_tm_rapi_Rapi_CREATE_NEW 1L
#undef org_eclipse_tm_rapi_Rapi_CREATE_ALWAYS
#define org_eclipse_tm_rapi_Rapi_CREATE_ALWAYS 2L
#undef org_eclipse_tm_rapi_Rapi_OPEN_EXISTING
#define org_eclipse_tm_rapi_Rapi_OPEN_EXISTING 3L
#undef org_eclipse_tm_rapi_Rapi_OPEN_ALWAYS
#define org_eclipse_tm_rapi_Rapi_OPEN_ALWAYS 4L
#undef org_eclipse_tm_rapi_Rapi_TRUNCATE_EXISTING
#define org_eclipse_tm_rapi_Rapi_TRUNCATE_EXISTING 5L
#undef org_eclipse_tm_rapi_Rapi_FILE_ATTRIBUTE_ARCHIVE
#define org_eclipse_tm_rapi_Rapi_FILE_ATTRIBUTE_ARCHIVE 32L
#undef org_eclipse_tm_rapi_Rapi_FILE_ATTRIBUTE_COMPRESSED
#define org_eclipse_tm_rapi_Rapi_FILE_ATTRIBUTE_COMPRESSED 2048L
#undef org_eclipse_tm_rapi_Rapi_FILE_ATTRIBUTE_DIRECTORY
#define org_eclipse_tm_rapi_Rapi_FILE_ATTRIBUTE_DIRECTORY 16L
#undef org_eclipse_tm_rapi_Rapi_FILE_ATTRIBUTE_ENCRYPTED
#define org_eclipse_tm_rapi_Rapi_FILE_ATTRIBUTE_ENCRYPTED 16384L
#undef org_eclipse_tm_rapi_Rapi_FILE_ATTRIBUTE_HIDDEN
#define org_eclipse_tm_rapi_Rapi_FILE_ATTRIBUTE_HIDDEN 2L
#undef org_eclipse_tm_rapi_Rapi_FILE_ATTRIBUTE_INROM
#define org_eclipse_tm_rapi_Rapi_FILE_ATTRIBUTE_INROM 64L
#undef org_eclipse_tm_rapi_Rapi_FILE_ATTRIBUTE_NORMAL
#define org_eclipse_tm_rapi_Rapi_FILE_ATTRIBUTE_NORMAL 128L
#undef org_eclipse_tm_rapi_Rapi_FILE_ATTRIBUTE_READONLY
#define org_eclipse_tm_rapi_Rapi_FILE_ATTRIBUTE_READONLY 1L
#undef org_eclipse_tm_rapi_Rapi_FILE_ATTRIBUTE_REPARSE_POINT
#define org_eclipse_tm_rapi_Rapi_FILE_ATTRIBUTE_REPARSE_POINT 1024L
#undef org_eclipse_tm_rapi_Rapi_FILE_ATTRIBUTE_ROMMODULE
#define org_eclipse_tm_rapi_Rapi_FILE_ATTRIBUTE_ROMMODULE 8192L
#undef org_eclipse_tm_rapi_Rapi_FILE_ATTRIBUTE_SPARSE_FILE
#define org_eclipse_tm_rapi_Rapi_FILE_ATTRIBUTE_SPARSE_FILE 512L
#undef org_eclipse_tm_rapi_Rapi_FILE_ATTRIBUTE_SYSTEM
#define org_eclipse_tm_rapi_Rapi_FILE_ATTRIBUTE_SYSTEM 4L
#undef org_eclipse_tm_rapi_Rapi_FILE_ATTRIBUTE_TEMPORARY
#define org_eclipse_tm_rapi_Rapi_FILE_ATTRIBUTE_TEMPORARY 256L
#undef org_eclipse_tm_rapi_Rapi_FILE_FLAG_WRITE_THROUGH
#define org_eclipse_tm_rapi_Rapi_FILE_FLAG_WRITE_THROUGH -2147483648L
#undef org_eclipse_tm_rapi_Rapi_FILE_FLAG_OVERLAPPED
#define org_eclipse_tm_rapi_Rapi_FILE_FLAG_OVERLAPPED 1073741824L
#undef org_eclipse_tm_rapi_Rapi_FILE_FLAG_RANDOM_ACCESS
#define org_eclipse_tm_rapi_Rapi_FILE_FLAG_RANDOM_ACCESS 268435456L
#undef org_eclipse_tm_rapi_Rapi_FILE_FLAG_SEQUENTIAL_SCAN
#define org_eclipse_tm_rapi_Rapi_FILE_FLAG_SEQUENTIAL_SCAN 134217728L
#undef org_eclipse_tm_rapi_Rapi_FAF_ATTRIB_CHILDREN
#define org_eclipse_tm_rapi_Rapi_FAF_ATTRIB_CHILDREN 4096L
#undef org_eclipse_tm_rapi_Rapi_FAF_ATTRIB_NO_HIDDEN
#define org_eclipse_tm_rapi_Rapi_FAF_ATTRIB_NO_HIDDEN 8192L
#undef org_eclipse_tm_rapi_Rapi_FAF_FOLDERS_ONLY
#define org_eclipse_tm_rapi_Rapi_FAF_FOLDERS_ONLY 16384L
#undef org_eclipse_tm_rapi_Rapi_FAF_NO_HIDDEN_SYS_ROMMODULES
#define org_eclipse_tm_rapi_Rapi_FAF_NO_HIDDEN_SYS_ROMMODULES 32768L
#undef org_eclipse_tm_rapi_Rapi_FAF_GETTARGET
#define org_eclipse_tm_rapi_Rapi_FAF_GETTARGET 65536L
#undef org_eclipse_tm_rapi_Rapi_FAF_ATTRIBUTES
#define org_eclipse_tm_rapi_Rapi_FAF_ATTRIBUTES 1L
#undef org_eclipse_tm_rapi_Rapi_FAF_CREATION_TIME
#define org_eclipse_tm_rapi_Rapi_FAF_CREATION_TIME 2L
#undef org_eclipse_tm_rapi_Rapi_FAF_LASTACCESS_TIME
#define org_eclipse_tm_rapi_Rapi_FAF_LASTACCESS_TIME 4L
#undef org_eclipse_tm_rapi_Rapi_FAF_LASTWRITE_TIME
#define org_eclipse_tm_rapi_Rapi_FAF_LASTWRITE_TIME 8L
#undef org_eclipse_tm_rapi_Rapi_FAF_SIZE_HIGH
#define org_eclipse_tm_rapi_Rapi_FAF_SIZE_HIGH 16L
#undef org_eclipse_tm_rapi_Rapi_FAF_SIZE_LOW
#define org_eclipse_tm_rapi_Rapi_FAF_SIZE_LOW 32L
#undef org_eclipse_tm_rapi_Rapi_FAF_OID
#define org_eclipse_tm_rapi_Rapi_FAF_OID 64L
#undef org_eclipse_tm_rapi_Rapi_FAF_NAME
#define org_eclipse_tm_rapi_Rapi_FAF_NAME 128L
#undef org_eclipse_tm_rapi_Rapi_INVALID_HANDLE_VALUE
#define org_eclipse_tm_rapi_Rapi_INVALID_HANDLE_VALUE -1L
#undef org_eclipse_tm_rapi_Rapi_TIME_DIFF
#define org_eclipse_tm_rapi_Rapi_TIME_DIFF 11644473600000i64
#undef org_eclipse_tm_rapi_Rapi_COINIT_MULTITHREADED
#define org_eclipse_tm_rapi_Rapi_COINIT_MULTITHREADED 0L
#undef org_eclipse_tm_rapi_Rapi_COINIT_APARTMENTTHREADED
#define org_eclipse_tm_rapi_Rapi_COINIT_APARTMENTTHREADED 2L
#undef org_eclipse_tm_rapi_Rapi_COINIT_DISABLE_OLE1DDE
#define org_eclipse_tm_rapi_Rapi_COINIT_DISABLE_OLE1DDE 4L
#undef org_eclipse_tm_rapi_Rapi_COINIT_SPEED_OVER_MEMORY
#define org_eclipse_tm_rapi_Rapi_COINIT_SPEED_OVER_MEMORY 8L
/*
 * Class:     org_eclipse_tm_rapi_Rapi
 * Method:    CoInitializeEx
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_eclipse_tm_rapi_Rapi_CoInitializeEx
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_eclipse_tm_rapi_Rapi
 * Method:    CoUninitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_eclipse_tm_rapi_Rapi_CoUninitialize
  (JNIEnv *, jclass);

/*
 * Class:     org_eclipse_tm_rapi_Rapi
 * Method:    CreateRapiDesktop
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_org_eclipse_tm_rapi_Rapi_CreateRapiDesktop
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     org_eclipse_tm_rapi_Rapi
 * Method:    ReleaseIUnknown
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_tm_rapi_Rapi_ReleaseIUnknown
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
