/*******************************************************************************
* Copyright (c) 2006, 2008 IBM Corporation and others.
* All rights reserved. This program and the accompanying materials
* are made available under the terms of the Eclipse Public License v1.0
* which accompanies this distribution, and is available at
* http://www.eclipse.org/legal/epl_v10.html
*
* Contributors:
*     IBM Corporation - initial API and implementation
*********************************************************************************/

// This file was generated by LPG

package org.eclipse.cdt.internal.core.dom.lrparser.cpp;

import lpg.lpgjavaruntime.*;

import java.util.*;

import org.eclipse.cdt.core.dom.ast.*;
import org.eclipse.cdt.core.dom.ast.cpp.*;
import org.eclipse.cdt.core.dom.lrparser.action.cpp.CPPASTNodeFactory;
import org.eclipse.cdt.core.dom.lrparser.action.cpp.CPPBuildASTParserAction;
import org.eclipse.cdt.core.dom.lrparser.IParser;
import org.eclipse.cdt.core.dom.lrparser.IParserActionTokenProvider;
import org.eclipse.cdt.core.dom.lrparser.util.DebugUtil;

import org.eclipse.cdt.core.dom.lrparser.action.ITokenMap;
import org.eclipse.cdt.core.dom.lrparser.action.TokenMap;

public class CPPNoCastExpressionParser extends PrsStream implements RuleAction , IParserActionTokenProvider, IParser 
{
    private static ParseTable prs = new CPPNoCastExpressionParserprs();
    private BacktrackingParser btParser;

    public BacktrackingParser getParser() { return btParser; }
    private void setResult(Object object) { btParser.setSym1(object); }
    public Object getRhsSym(int i) { return btParser.getSym(i); }

    public int getRhsTokenIndex(int i) { return btParser.getToken(i); }
    public IToken getRhsIToken(int i) { return super.getIToken(getRhsTokenIndex(i)); }
    
    public int getRhsFirstTokenIndex(int i) { return btParser.getFirstToken(i); }
    public IToken getRhsFirstIToken(int i) { return super.getIToken(getRhsFirstTokenIndex(i)); }

    public int getRhsLastTokenIndex(int i) { return btParser.getLastToken(i); }
    public IToken getRhsLastIToken(int i) { return super.getIToken(getRhsLastTokenIndex(i)); }

    public int getLeftSpan() { return btParser.getFirstToken(); }
    public IToken getLeftIToken()  { return super.getIToken(getLeftSpan()); }

    public int getRightSpan() { return btParser.getLastToken(); }
    public IToken getRightIToken() { return super.getIToken(getRightSpan()); }

    public int getRhsErrorTokenIndex(int i)
    {
        int index = btParser.getToken(i);
        IToken err = super.getIToken(index);
        return (err instanceof ErrorToken ? index : 0);
    }
    public ErrorToken getRhsErrorIToken(int i)
    {
        int index = btParser.getToken(i);
        IToken err = super.getIToken(index);
        return (ErrorToken) (err instanceof ErrorToken ? err : null);
    }

    public CPPNoCastExpressionParser(LexStream lexStream)
    {
        super(lexStream);

        try
        {
            super.remapTerminalSymbols(orderedTerminalSymbols(), CPPNoCastExpressionParserprs.EOFT_SYMBOL);
        }
        catch(NullExportedSymbolsException e) {
        }
        catch(NullTerminalSymbolsException e) {
        }
        catch(UnimplementedTerminalsException e)
        {
            java.util.ArrayList unimplemented_symbols = e.getSymbols();
            System.out.println("The Lexer will not scan the following token(s):");
            for (int i = 0; i < unimplemented_symbols.size(); i++)
            {
                Integer id = (Integer) unimplemented_symbols.get(i);
                System.out.println("    " + CPPNoCastExpressionParsersym.orderedTerminalSymbols[id.intValue()]);               
            }
            System.out.println();                        
        }
        catch(UndefinedEofSymbolException e)
        {
            throw new Error(new UndefinedEofSymbolException
                                ("The Lexer does not implement the Eof symbol " +
                                 CPPNoCastExpressionParsersym.orderedTerminalSymbols[CPPNoCastExpressionParserprs.EOFT_SYMBOL]));
        } 
    }

    public String[] orderedTerminalSymbols() { return CPPNoCastExpressionParsersym.orderedTerminalSymbols; }
    public String getTokenKindName(int kind) { return CPPNoCastExpressionParsersym.orderedTerminalSymbols[kind]; }
    public int getEOFTokenKind() { return CPPNoCastExpressionParserprs.EOFT_SYMBOL; }
    public PrsStream getParseStream() { return (PrsStream) this; }
    
    //
    // Report error message for given error_token.
    //
    public final void reportErrorTokenMessage(int error_token, String msg)
    {
        int firsttok = super.getFirstErrorToken(error_token),
            lasttok = super.getLastErrorToken(error_token);
        String location = super.getFileName() + ':' +
                          (firsttok > lasttok
                                    ? (super.getEndLine(lasttok) + ":" + super.getEndColumn(lasttok))
                                    : (super.getLine(error_token) + ":" +
                                       super.getColumn(error_token) + ":" +
                                       super.getEndLine(error_token) + ":" +
                                       super.getEndColumn(error_token)))
                          + ": ";
        super.reportError((firsttok > lasttok ? ParseErrorCodes.INSERTION_CODE : ParseErrorCodes.SUBSTITUTION_CODE), location, msg);
    }

    public Object parser()
    {
        return parser(null, 0);
    }
    
    public Object parser(Monitor monitor)
    {
        return parser(monitor, 0);
    }
    
    public Object parser(int error_repair_count)
    {
        return parser(null, error_repair_count);
    }

    public Object parser(Monitor monitor, int error_repair_count)
    {
        try
        {
            btParser = new BacktrackingParser(monitor, (TokenStream) this, prs, (RuleAction) this);
        }
        catch (NotBacktrackParseTableException e)
        {
            throw new Error(new NotBacktrackParseTableException
                                ("Regenerate CPPNoCastExpressionParserprs.java with -BACKTRACK option"));
        }
        catch (BadParseSymFileException e)
        {
            throw new Error(new BadParseSymFileException("Bad Parser Symbol File -- CPPNoCastExpressionParsersym.java"));
        }

        try
        {
            return (Object) btParser.parse(error_repair_count);
        }
        catch (BadParseException e)
        {
            reset(e.error_token); // point to error token
            DiagnoseParser diagnoseParser = new DiagnoseParser(this, prs);
            diagnoseParser.diagnose(e.error_token);
        }

        return null;
    }


private  CPPParserAction  action;	

// uncomment to use with backtracking parser
public CPPNoCastExpressionParser() {  // constructor
}

private void initActions(IASTTranslationUnit tu) {
    // binding resolution actions need access to IASTName nodes, temporary
    action = new  CPPParserAction ();
	//action.resolver = new  C99TypedefTrackerParserAction (this);
	action.builder  = new  CPPBuildASTParserAction ( CPPASTNodeFactory.DEFAULT_INSTANCE , this, tu);
	//action.builder.setTokenMap(CPPParsersym.orderedTerminalSymbols);
	
	// comment this line to use with backtracking parser
	//setParserAction(action);
}


public void addToken(IToken token) {
	token.setKind(mapKind(token.getKind()));
	super.addToken(token);
}


public IASTCompletionNode parse(IASTTranslationUnit tu) {
	// this has to be done, or... kaboom!
	setStreamLength(getSize());
	initActions(tu);
	
	final int errorRepairCount = -1;  // _1 means full error handling
	parser(null, errorRepairCount); // do the actual parse
	super.resetTokenStream(); // allow tokens to be garbage collected

	// the completion node may be null
	IASTCompletionNode compNode = action.builder.getASTCompletionNode();

	//action = null; // causes getSecondaryParseResult() to fail
	
	// Comment this line to use with backtracking parser
	//parserAction = null;
	
	return compNode;
}


public int getKind(int i) {
	int kind = super.getKind(i);
	
	// There used to be a special token kind for zero used to parser pure virtual function declarations.
	// But it turned out to be easier to just parse them as an init_declarator and programaticaly check
	// for pure virtual, see consumeMemberDeclaratorWithInitializer().
	
	//if(kind == CPPParsersym.TK_integer && "0".equals(getTokenText(i))) { //$NON-NLS-1$
	//	kind = CPPParsersym.TK_zero;
	//}
	
	// lexer feedback hack!
	//else if(kind == C99Parsersym.TK_identifier && action.resolver.isTypedef(getTokenText(i))) {
	//	kind = C99Parsersym.TK_TypedefName;
	//}
	
	return kind;
}


// uncomment this method to use with backtracking parser
public List getRuleTokens() {
    return Collections.unmodifiableList(getTokens().subList(getLeftSpan(), getRightSpan() + 1));
}


public IASTNode getSecondaryParseResult() {
	return  action.builder.getSecondaryParseResult();
}


private ITokenMap tokenMap = null;

public void setTokens(List<IToken> tokens) {
	resetTokenStream();
	addToken(new Token(null, 0, 0, 0)); // dummy token
	for(IToken token : tokens) {
		token.setKind(tokenMap.mapKind(token.getKind()));
		addToken(token);
	}
	addToken(new Token(null, 0, 0, CPPNoCastExpressionParsersym.TK_EOF_TOKEN));
}

public CPPNoCastExpressionParser(String[] mapFrom) {  // constructor
	tokenMap = new TokenMap(CPPNoCastExpressionParsersym.orderedTerminalSymbols, mapFrom);
}	



    public void ruleAction(int ruleNumber)
    {
        switch (ruleNumber)
        {
  
            //
            // Rule 1:  <openscope-ast> ::= $Empty
            //
            case 1: {       action.builder.
  openASTScope();                break;
            }
  
            //
            // Rule 4:  <placeholder> ::= $Empty
            //
            case 4: {       action.builder.
  consumePlaceHolder();                break;
            }
  
            //
            // Rule 5:  <empty> ::= $Empty
            //
            case 5: {       action.builder.
  consumeEmpty();                break;
            }
   
            //
            // Rule 10:  translation_unit ::= external_declaration_list
            //
            case 10: {       action.builder.
   consumeTranslationUnit();                break;
            }  
   
            //
            // Rule 11:  translation_unit ::= $Empty
            //
            case 11: {       action.builder.
   consumeTranslationUnit();                break;
            }  
   
            //
            // Rule 15:  external_declaration ::= ERROR_TOKEN
            //
            case 15: {       action.builder.
   consumeDeclarationProblem();                 break;
            }  
   
            //
            // Rule 16:  literal ::= integer
            //
            case 16: {       action.builder.
   consumeExpressionLiteral(ICPPASTLiteralExpression.lk_integer_constant);                break;
            }  
   
            //
            // Rule 17:  literal ::= 0
            //
            case 17: {       action.builder.
   consumeExpressionLiteral(ICPPASTLiteralExpression.lk_integer_constant);                break;
            }  
   
            //
            // Rule 18:  literal ::= floating
            //
            case 18: {       action.builder.
   consumeExpressionLiteral(ICPPASTLiteralExpression.lk_float_constant);                break;
            }  
   
            //
            // Rule 19:  literal ::= charconst
            //
            case 19: {       action.builder.
   consumeExpressionLiteral(ICPPASTLiteralExpression.lk_char_constant);                break;
            }  
   
            //
            // Rule 20:  literal ::= stringlit
            //
            case 20: {       action.builder.
   consumeExpressionLiteral(ICPPASTLiteralExpression.lk_string_literal);                break;
            }  
   
            //
            // Rule 21:  literal ::= true
            //
            case 21: {       action.builder.
   consumeExpressionLiteral(ICPPASTLiteralExpression.lk_true);                break;
            }  
   
            //
            // Rule 22:  literal ::= false
            //
            case 22: {       action.builder.
   consumeExpressionLiteral(ICPPASTLiteralExpression.lk_false);                break;
            }  
   
            //
            // Rule 23:  literal ::= this
            //
            case 23: {       action.builder.
   consumeExpressionLiteral(ICPPASTLiteralExpression.lk_this);                break;
            }  
   
            //
            // Rule 25:  primary_expression ::= ( expression )
            //
            case 25: {       action.builder.
   consumeExpressionBracketed();                 break;
            }  
   
            //
            // Rule 27:  id_expression ::= qualified_or_unqualified_name
            //
            case 27: {       action.builder.
   consumeExpressionName();                 break;
            }  
   
            //
            // Rule 34:  unqualified_id_name ::= ~ class_name
            //
            case 34: {       action.builder.
   consumeDestructorName();                 break;
            }  
   
            //
            // Rule 35:  identifier_name ::= identifier
            //
            case 35: {       action.builder.
   consumeIdentifierName();                 break;
            }  
   
            //
            // Rule 36:  template_opt ::= template
            //
            case 36: {       action.builder.
   consumePlaceHolder();                 break;
            }  
   
            //
            // Rule 37:  template_opt ::= $Empty
            //
            case 37: {       action.builder.
   consumeEmpty();                 break;
            }  
   
            //
            // Rule 38:  dcolon_opt ::= ::
            //
            case 38: {       action.builder.
   consumePlaceHolder();                 break;
            }  
   
            //
            // Rule 39:  dcolon_opt ::= $Empty
            //
            case 39: {       action.builder.
   consumeEmpty();                 break;
            }  
   
            //
            // Rule 40:  qualified_id_name ::= dcolon_opt nested_name_specifier template_opt unqualified_id_name
            //
            case 40: {       action.builder.
   consumeQualifiedId(true);                 break;
            }  
   
            //
            // Rule 41:  qualified_id_name ::= :: identifier_name
            //
            case 41: {       action.builder.
   consumeGlobalQualifiedId();                 break;
            }  
   
            //
            // Rule 42:  qualified_id_name ::= :: operator_function_id_name
            //
            case 42: {       action.builder.
   consumeGlobalQualifiedId();                 break;
            }  
   
            //
            // Rule 43:  qualified_id_name ::= :: template_id_name
            //
            case 43: {       action.builder.
   consumeGlobalQualifiedId();                 break;
            }  
   
            //
            // Rule 44:  nested_name_specifier ::= class_or_namespace_name :: nested_name_specifier_with_template
            //
            case 44: {       action.builder.
   consumeNestedNameSpecifier(true);                 break;
            }  
   
            //
            // Rule 45:  nested_name_specifier ::= class_or_namespace_name ::
            //
            case 45: {       action.builder.
   consumeNestedNameSpecifier(false);                 break;
            }  
   
            //
            // Rule 46:  nested_name_specifier_with_template ::= class_or_namespace_name_with_template :: nested_name_specifier_with_template
            //
            case 46: {       action.builder.
   consumeNestedNameSpecifier(true);                 break;
            }  
   
            //
            // Rule 47:  nested_name_specifier_with_template ::= class_or_namespace_name_with_template ::
            //
            case 47: {       action.builder.
   consumeNestedNameSpecifier(false);                 break;
            }  
   
            //
            // Rule 48:  class_or_namespace_name_with_template ::= template_opt class_or_namespace_name
            //
            case 48: {       action.builder.
   consumeNameWithTemplateKeyword();                 break;
            }  
   
            //
            // Rule 50:  nested_name_specifier_opt ::= $Empty
            //
            case 50: {       action.builder.
   consumeNestedNameSpecifierEmpty();                 break;
            }  
   
            //
            // Rule 54:  postfix_expression ::= postfix_expression [ expression ]
            //
            case 54: {       action.builder.
   consumeExpressionArraySubscript();                 break;
            }  
   
            //
            // Rule 55:  postfix_expression ::= postfix_expression ( expression_list_opt )
            //
            case 55: {       action.builder.
   consumeExpressionFunctionCall();                 break;
            }  
   
            //
            // Rule 56:  postfix_expression ::= simple_type_specifier ( expression_list_opt )
            //
            case 56: {       action.builder.
   consumeExpressionSimpleTypeConstructor();                break;
            }  
   
            //
            // Rule 57:  postfix_expression ::= typename dcolon_opt nested_name_specifier <empty> identifier_name ( expression_list_opt )
            //
            case 57: {       action.builder.
   consumeExpressionTypeName();                break;
            }  
   
            //
            // Rule 58:  postfix_expression ::= typename dcolon_opt nested_name_specifier template_opt template_id_name ( expression_list_opt )
            //
            case 58: {       action.builder.
   consumeExpressionTypeName();                break;
            }  
   
            //
            // Rule 59:  postfix_expression ::= postfix_expression . qualified_or_unqualified_name
            //
            case 59: {       action.builder.
   consumeExpressionFieldReference(false, false);                 break;
            }  
   
            //
            // Rule 60:  postfix_expression ::= postfix_expression -> qualified_or_unqualified_name
            //
            case 60: {       action.builder.
   consumeExpressionFieldReference(true, false);                 break;
            }  
   
            //
            // Rule 61:  postfix_expression ::= postfix_expression . template qualified_or_unqualified_name
            //
            case 61: {       action.builder.
   consumeExpressionFieldReference(false, true);                 break;
            }  
   
            //
            // Rule 62:  postfix_expression ::= postfix_expression -> template qualified_or_unqualified_name
            //
            case 62: {       action.builder.
   consumeExpressionFieldReference(true, true);                 break;
            }  
   
            //
            // Rule 63:  postfix_expression ::= postfix_expression . pseudo_destructor_name
            //
            case 63: {       action.builder.
   consumeExpressionFieldReference(false, false);                 break;
            }  
   
            //
            // Rule 64:  postfix_expression ::= postfix_expression -> pseudo_destructor_name
            //
            case 64: {       action.builder.
   consumeExpressionFieldReference(true, false);                 break;
            }  
   
            //
            // Rule 65:  postfix_expression ::= postfix_expression ++
            //
            case 65: {       action.builder.
   consumeExpressionUnaryOperator(IASTUnaryExpression.op_postFixIncr);                 break;
            }  
   
            //
            // Rule 66:  postfix_expression ::= postfix_expression --
            //
            case 66: {       action.builder.
   consumeExpressionUnaryOperator(IASTUnaryExpression.op_postFixDecr);                 break;
            }  
   
            //
            // Rule 67:  postfix_expression ::= dynamic_cast < type_id > ( expression )
            //
            case 67: {       action.builder.
   consumeExpressionCast(ICPPASTCastExpression.op_dynamic_cast);                 break;
            }  
   
            //
            // Rule 68:  postfix_expression ::= static_cast < type_id > ( expression )
            //
            case 68: {       action.builder.
   consumeExpressionCast(ICPPASTCastExpression.op_static_cast);                 break;
            }  
   
            //
            // Rule 69:  postfix_expression ::= reinterpret_cast < type_id > ( expression )
            //
            case 69: {       action.builder.
   consumeExpressionCast(ICPPASTCastExpression.op_reinterpret_cast);                 break;
            }  
   
            //
            // Rule 70:  postfix_expression ::= const_cast < type_id > ( expression )
            //
            case 70: {       action.builder.
   consumeExpressionCast(ICPPASTCastExpression.op_const_cast);                 break;
            }  
   
            //
            // Rule 71:  postfix_expression ::= typeid ( expression )
            //
            case 71: {       action.builder.
   consumeExpressionUnaryOperator(ICPPASTUnaryExpression.op_typeid);                 break;
            }  
   
            //
            // Rule 72:  postfix_expression ::= typeid ( type_id )
            //
            case 72: {       action.builder.
   consumeExpressionTypeId(ICPPASTTypeIdExpression.op_typeid);                break;
            }  
   
            //
            // Rule 73:  pseudo_destructor_name ::= dcolon_opt nested_name_specifier_opt type_name :: ~ type_name
            //
            case 73: {       action.builder.
   consumePsudoDestructorName(true);                 break;
            }  
   
            //
            // Rule 74:  pseudo_destructor_name ::= dcolon_opt nested_name_specifier template template_id_name :: ~ type_name
            //
            case 74: {       action.builder.
   consumePsudoDestructorName(true);                 break;
            }  
   
            //
            // Rule 75:  pseudo_destructor_name ::= dcolon_opt nested_name_specifier_opt ~ type_name
            //
            case 75: {       action.builder.
   consumePsudoDestructorName(false);                 break;
            }  
   
            //
            // Rule 79:  unary_expression ::= ++ cast_expression
            //
            case 79: {       action.builder.
   consumeExpressionUnaryOperator(IASTUnaryExpression.op_prefixIncr);                 break;
            }  
   
            //
            // Rule 80:  unary_expression ::= -- cast_expression
            //
            case 80: {       action.builder.
   consumeExpressionUnaryOperator(IASTUnaryExpression.op_prefixDecr);                 break;
            }  
   
            //
            // Rule 81:  unary_expression ::= & cast_expression
            //
            case 81: {       action.builder.
   consumeExpressionUnaryOperator(IASTUnaryExpression.op_amper);                 break;
            }  
   
            //
            // Rule 82:  unary_expression ::= * cast_expression
            //
            case 82: {       action.builder.
   consumeExpressionUnaryOperator(IASTUnaryExpression.op_star);                 break;
            }  
   
            //
            // Rule 83:  unary_expression ::= + cast_expression
            //
            case 83: {       action.builder.
   consumeExpressionUnaryOperator(IASTUnaryExpression.op_plus);                 break;
            }  
   
            //
            // Rule 84:  unary_expression ::= - cast_expression
            //
            case 84: {       action.builder.
   consumeExpressionUnaryOperator(IASTUnaryExpression.op_minus);                 break;
            }  
   
            //
            // Rule 85:  unary_expression ::= ~ cast_expression
            //
            case 85: {       action.builder.
   consumeExpressionUnaryOperator(IASTUnaryExpression.op_tilde);                 break;
            }  
   
            //
            // Rule 86:  unary_expression ::= ! cast_expression
            //
            case 86: {       action.builder.
   consumeExpressionUnaryOperator(IASTUnaryExpression.op_not);                 break;
            }  
   
            //
            // Rule 87:  unary_expression ::= sizeof unary_expression
            //
            case 87: {       action.builder.
   consumeExpressionUnaryOperator(IASTUnaryExpression.op_sizeof);                 break;
            }  
   
            //
            // Rule 88:  unary_expression ::= sizeof ( type_id )
            //
            case 88: {       action.builder.
   consumeExpressionTypeId(ICPPASTTypeIdExpression.op_sizeof);                break;
            }  
   
            //
            // Rule 89:  new_expression ::= dcolon_opt new new_placement_opt new_type_id <openscope-ast> new_array_expressions_opt new_initializer_opt
            //
            case 89: {       action.builder.
   consumeExpressionNew(true);                 break;
            }  
   
            //
            // Rule 90:  new_expression ::= dcolon_opt new new_placement_opt ( type_id ) new_initializer_opt
            //
            case 90: {       action.builder.
   consumeExpressionNew(false);                 break;
            }  
   
            //
            // Rule 93:  new_placement_opt ::= $Empty
            //
            case 93: {       action.builder.
   consumeEmpty();                 break;
            }  
   
            //
            // Rule 94:  new_type_id ::= type_specifier_seq
            //
            case 94: {       action.builder.
   consumeTypeId(false);                 break;
            }  
   
            //
            // Rule 95:  new_type_id ::= type_specifier_seq new_declarator
            //
            case 95: {       action.builder.
   consumeTypeId(true);                 break;
            }  
   
            //
            // Rule 96:  new_declarator ::= <openscope-ast> new_pointer_operators
            //
            case 96: {       action.builder.
   consumeNewDeclarator();                break;
            }  
   
            //
            // Rule 105:  new_initializer_opt ::= $Empty
            //
            case 105: {       action.builder.
   consumeEmpty();                 break;
            }  
   
            //
            // Rule 106:  delete_expression ::= dcolon_opt delete cast_expression
            //
            case 106: {       action.builder.
   consumeExpressionDelete(false);                 break;
            }  
   
            //
            // Rule 107:  delete_expression ::= dcolon_opt delete [ ] cast_expression
            //
            case 107: {       action.builder.
   consumeExpressionDelete(true);                 break;
            }  
   
            //
            // Rule 110:  pm_expression ::= pm_expression .* cast_expression
            //
            case 110: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_pmdot);                 break;
            }  
   
            //
            // Rule 111:  pm_expression ::= pm_expression ->* cast_expression
            //
            case 111: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_pmarrow);                 break;
            }  
   
            //
            // Rule 113:  multiplicative_expression ::= multiplicative_expression * pm_expression
            //
            case 113: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_multiply);                 break;
            }  
   
            //
            // Rule 114:  multiplicative_expression ::= multiplicative_expression / pm_expression
            //
            case 114: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_divide);                 break;
            }  
   
            //
            // Rule 115:  multiplicative_expression ::= multiplicative_expression % pm_expression
            //
            case 115: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_modulo);                 break;
            }  
   
            //
            // Rule 117:  additive_expression ::= additive_expression + multiplicative_expression
            //
            case 117: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_plus);                 break;
            }  
   
            //
            // Rule 118:  additive_expression ::= additive_expression - multiplicative_expression
            //
            case 118: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_minus);                 break;
            }  
   
            //
            // Rule 120:  shift_expression ::= shift_expression << additive_expression
            //
            case 120: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_shiftLeft);                 break;
            }  
   
            //
            // Rule 121:  shift_expression ::= shift_expression >> additive_expression
            //
            case 121: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_shiftRight);                 break;
            }  
   
            //
            // Rule 123:  relational_expression ::= relational_expression < shift_expression
            //
            case 123: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_lessThan);                 break;
            }  
   
            //
            // Rule 124:  relational_expression ::= relational_expression > shift_expression
            //
            case 124: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_greaterThan);                 break;
            }  
   
            //
            // Rule 125:  relational_expression ::= relational_expression <= shift_expression
            //
            case 125: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_lessEqual);                 break;
            }  
   
            //
            // Rule 126:  relational_expression ::= relational_expression >= shift_expression
            //
            case 126: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_greaterEqual);                 break;
            }  
   
            //
            // Rule 128:  equality_expression ::= equality_expression == relational_expression
            //
            case 128: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_equals);                 break;
            }  
   
            //
            // Rule 129:  equality_expression ::= equality_expression != relational_expression
            //
            case 129: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_notequals);                 break;
            }  
   
            //
            // Rule 131:  and_expression ::= and_expression & equality_expression
            //
            case 131: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_binaryAnd);                 break;
            }  
   
            //
            // Rule 133:  exclusive_or_expression ::= exclusive_or_expression ^ and_expression
            //
            case 133: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_binaryXor);                 break;
            }  
   
            //
            // Rule 135:  inclusive_or_expression ::= inclusive_or_expression | exclusive_or_expression
            //
            case 135: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_binaryOr);                 break;
            }  
   
            //
            // Rule 137:  logical_and_expression ::= logical_and_expression && inclusive_or_expression
            //
            case 137: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_logicalAnd);                 break;
            }  
   
            //
            // Rule 139:  logical_or_expression ::= logical_or_expression || logical_and_expression
            //
            case 139: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_logicalOr);                 break;
            }  
   
            //
            // Rule 141:  conditional_expression ::= logical_or_expression ? expression : assignment_expression
            //
            case 141: {       action.builder.
   consumeExpressionConditional();                 break;
            }  
   
            //
            // Rule 142:  throw_expression ::= throw
            //
            case 142: {       action.builder.
   consumeExpressionThrow(false);                 break;
            }  
   
            //
            // Rule 143:  throw_expression ::= throw assignment_expression
            //
            case 143: {       action.builder.
   consumeExpressionThrow(true);                 break;
            }  
   
            //
            // Rule 146:  assignment_expression ::= logical_or_expression = assignment_expression
            //
            case 146: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_assign);                 break;
            }  
   
            //
            // Rule 147:  assignment_expression ::= logical_or_expression *= assignment_expression
            //
            case 147: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_multiplyAssign);                 break;
            }  
   
            //
            // Rule 148:  assignment_expression ::= logical_or_expression /= assignment_expression
            //
            case 148: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_divideAssign);                 break;
            }  
   
            //
            // Rule 149:  assignment_expression ::= logical_or_expression %= assignment_expression
            //
            case 149: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_moduloAssign);                 break;
            }  
   
            //
            // Rule 150:  assignment_expression ::= logical_or_expression += assignment_expression
            //
            case 150: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_plusAssign);                 break;
            }  
   
            //
            // Rule 151:  assignment_expression ::= logical_or_expression -= assignment_expression
            //
            case 151: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_minusAssign);                 break;
            }  
   
            //
            // Rule 152:  assignment_expression ::= logical_or_expression >>= assignment_expression
            //
            case 152: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_shiftRightAssign);                 break;
            }  
   
            //
            // Rule 153:  assignment_expression ::= logical_or_expression <<= assignment_expression
            //
            case 153: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_shiftLeftAssign);                 break;
            }  
   
            //
            // Rule 154:  assignment_expression ::= logical_or_expression &= assignment_expression
            //
            case 154: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_binaryAndAssign);                 break;
            }  
   
            //
            // Rule 155:  assignment_expression ::= logical_or_expression ^= assignment_expression
            //
            case 155: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_binaryXorAssign);                 break;
            }  
   
            //
            // Rule 156:  assignment_expression ::= logical_or_expression |= assignment_expression
            //
            case 156: {       action.builder.
   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_binaryOrAssign);                 break;
            }  
   
            //
            // Rule 158:  expression ::= ERROR_TOKEN
            //
            case 158: {       action.builder.
   consumeExpressionProblem();                break;
            }  
   
            //
            // Rule 159:  expression_list ::= <openscope-ast> expression_list_actual
            //
            case 159: {       action.builder.
   consumeExpressionList();                 break;
            }  
   
            //
            // Rule 163:  expression_list_opt ::= $Empty
            //
            case 163: {       action.builder.
   consumeEmpty();                 break;
            }  
   
            //
            // Rule 165:  expression_opt ::= $Empty
            //
            case 165: {       action.builder.
   consumeEmpty();                 break;
            }  
   
            //
            // Rule 168:  constant_expression_opt ::= $Empty
            //
            case 168: {       action.builder.
   consumeEmpty();                 break;
            }  
   
            //
            // Rule 177:  statement ::= ERROR_TOKEN
            //
            case 177: {       action.builder.
   consumeStatementProblem();                 break;
            }  
   
            //
            // Rule 178:  labeled_statement ::= identifier : statement
            //
            case 178: {       action.builder.
   consumeStatementLabeled();                 break;
            }  
   
            //
            // Rule 179:  labeled_statement ::= case constant_expression :
            //
            case 179: {       action.builder.
   consumeStatementCase();                 break;
            }  
   
            //
            // Rule 180:  labeled_statement ::= default :
            //
            case 180: {       action.builder.
   consumeStatementDefault();                 break;
            }  
   
            //
            // Rule 181:  expression_statement ::= expression ;
            //
            case 181: {       action.builder.
   consumeStatementExpression();                 break;
            }  
   
            //
            // Rule 182:  expression_statement ::= ;
            //
            case 182: {       action.builder.
   consumeStatementNull();                 break;
            }  
   
            //
            // Rule 183:  compound_statement ::= { <openscope-ast> statement_seq }
            //
            case 183: {       action.builder.
   consumeStatementCompoundStatement(true);                 break;
            }  
   
            //
            // Rule 184:  compound_statement ::= { }
            //
            case 184: {       action.builder.
   consumeStatementCompoundStatement(false);                 break;
            }  
   
            //
            // Rule 187:  selection_statement ::= if ( condition ) statement
            //
            case 187: {       action.builder.
   consumeStatementIf(false);                 break;
            }  
   
            //
            // Rule 188:  selection_statement ::= if ( condition ) statement else statement
            //
            case 188: {       action.builder.
   consumeStatementIf(true);                 break;
            }  
   
            //
            // Rule 189:  selection_statement ::= switch ( condition ) statement
            //
            case 189: {       action.builder.
   consumeStatementSwitch();                 break;
            }  
   
            //
            // Rule 191:  condition ::= type_specifier_seq declarator = assignment_expression
            //
            case 191: {       action.builder.
   consumeConditionDeclaration();                 break;
            }  
   
            //
            // Rule 192:  iteration_statement ::= while ( condition ) statement
            //
            case 192: {       action.builder.
   consumeStatementWhileLoop();                 break;
            }  
   
            //
            // Rule 193:  iteration_statement ::= do statement while ( expression ) ;
            //
            case 193: {       action.builder.
   consumeStatementDoLoop();                 break;
            }  
   
            //
            // Rule 194:  iteration_statement ::= for ( expression_opt ; expression_opt ; expression_opt ) statement
            //
            case 194: {       action.builder.
  consumeStatementForLoop();                break;
            }  
   
            //
            // Rule 195:  iteration_statement ::= for ( simple_declaration expression_opt ; expression_opt ) statement
            //
            case 195: {       action.builder.
  consumeStatementForLoop();                break;
            }  
   
            //
            // Rule 196:  jump_statement ::= break ;
            //
            case 196: {       action.builder.
   consumeStatementBreak();                 break;
            }  
   
            //
            // Rule 197:  jump_statement ::= continue ;
            //
            case 197: {       action.builder.
   consumeStatementContinue();                 break;
            }  
   
            //
            // Rule 198:  jump_statement ::= return expression ;
            //
            case 198: {       action.builder.
   consumeStatementReturn(true);                 break;
            }  
   
            //
            // Rule 199:  jump_statement ::= return ;
            //
            case 199: {       action.builder.
   consumeStatementReturn(false);                 break;
            }  
   
            //
            // Rule 200:  jump_statement ::= goto identifier ;
            //
            case 200: {       action.builder.
   consumeStatementGoto();                 break;
            }  
   
            //
            // Rule 201:  declaration_statement ::= block_declaration
            //
            case 201: {       action.builder.
   consumeStatementDeclaration();                 break;
            }  
   
            //
            // Rule 218:  simple_declaration ::= declaration_specifiers_opt <openscope-ast> init_declarator_list_opt ;
            //
            case 218: {       action.builder.
   consumeDeclarationSimple(true);                 break;
            }  
   
            //
            // Rule 219:  declaration_specifiers ::= <openscope-ast> simple_declaration_specifiers
            //
            case 219: {       action.builder.
   consumeDeclarationSpecifiersSimple();                 break;
            }  
   
            //
            // Rule 220:  declaration_specifiers ::= <openscope-ast> class_declaration_specifiers
            //
            case 220: {       action.builder.
   consumeDeclarationSpecifiersComposite();                 break;
            }  
   
            //
            // Rule 221:  declaration_specifiers ::= <openscope-ast> elaborated_declaration_specifiers
            //
            case 221: {       action.builder.
   consumeDeclarationSpecifiersComposite();                 break;
            }  
   
            //
            // Rule 222:  declaration_specifiers ::= <openscope-ast> enum_declaration_specifiers
            //
            case 222: {       action.builder.
   consumeDeclarationSpecifiersComposite();                 break;
            }  
   
            //
            // Rule 223:  declaration_specifiers ::= <openscope-ast> type_name_declaration_specifiers
            //
            case 223: {       action.builder.
   consumeDeclarationSpecifiersTypeName();                 break;
            }  
   
            //
            // Rule 225:  declaration_specifiers_opt ::= $Empty
            //
            case 225: {       action.builder.
   consumeEmpty();                 break;
            }  
   
            //
            // Rule 229:  no_type_declaration_specifier ::= friend
            //
            case 229: {       action.builder.
   consumeDeclSpecToken();                break;
            }  
   
            //
            // Rule 230:  no_type_declaration_specifier ::= typedef
            //
            case 230: {       action.builder.
   consumeDeclSpecToken();                break;
            }  
   
            //
            // Rule 259:  simple_type_specifier ::= simple_type_specifier_token
            //
            case 259: {       action.builder.
   consumeDeclSpecToken();                break;
            }  
   
            //
            // Rule 275:  type_name_specifier ::= dcolon_opt nested_name_specifier_opt type_name
            //
            case 275: {       action.builder.
   consumeQualifiedId(false);                 break;
            }  
   
            //
            // Rule 276:  type_name_specifier ::= dcolon_opt nested_name_specifier template template_id_name
            //
            case 276: {       action.builder.
   consumeQualifiedId(false);                 break;
            }  
   
            //
            // Rule 277:  type_name_specifier ::= typename dcolon_opt nested_name_specifier identifier_name
            //
            case 277: {       action.builder.
   consumeQualifiedId(false);                 break;
            }  
   
            //
            // Rule 278:  type_name_specifier ::= typename dcolon_opt nested_name_specifier template_opt template_id_name
            //
            case 278: {       action.builder.
   consumeQualifiedId(true);                 break;
            }  
   
            //
            // Rule 279:  elaborated_type_specifier ::= class_keyword dcolon_opt nested_name_specifier_opt identifier_name
            //
            case 279: {       action.builder.
   consumeTypeSpecifierElaborated(false);                 break;
            }  
   
            //
            // Rule 280:  elaborated_type_specifier ::= class_keyword dcolon_opt nested_name_specifier_opt template_opt template_id_name
            //
            case 280: {       action.builder.
   consumeTypeSpecifierElaborated(true);                  break;
            }  
   
            //
            // Rule 281:  elaborated_type_specifier ::= enum dcolon_opt nested_name_specifier_opt identifier_name
            //
            case 281: {       action.builder.
   consumeTypeSpecifierElaborated(false);                 break;
            }  
   
            //
            // Rule 283:  enum_specifier ::= enum { <openscope-ast> enumerator_list_opt }
            //
            case 283: {       action.builder.
   consumeTypeSpecifierEnumeration(false);                break;
            }  
   
            //
            // Rule 284:  enum_specifier ::= enum identifier { <openscope-ast> enumerator_list_opt }
            //
            case 284: {       action.builder.
   consumeTypeSpecifierEnumeration(true);                break;
            }  
   
            //
            // Rule 289:  enumerator_definition ::= enumerator
            //
            case 289: {       action.builder.
   consumeEnumerator(false);                break;
            }  
   
            //
            // Rule 290:  enumerator_definition ::= enumerator = constant_expression
            //
            case 290: {       action.builder.
   consumeEnumerator(true);                break;
            }  
   
            //
            // Rule 299:  original_namespace_definition ::= namespace identifier_name { <openscope-ast> declaration_seq_opt }
            //
            case 299: {       action.builder.
   consumeNamespaceDefinition(true);                 break;
            }  
   
            //
            // Rule 300:  extension_namespace_definition ::= namespace original_namespace_name { <openscope-ast> declaration_seq_opt }
            //
            case 300: {       action.builder.
   consumeNamespaceDefinition(true);                 break;
            }  
   
            //
            // Rule 301:  unnamed_namespace_definition ::= namespace { <openscope-ast> declaration_seq_opt }
            //
            case 301: {       action.builder.
   consumeNamespaceDefinition(false);                 break;
            }  
   
            //
            // Rule 303:  namespace_alias_definition ::= namespace identifier = dcolon_opt nested_name_specifier_opt namespace_name ;
            //
            case 303: {       action.builder.
   consumeNamespaceAliasDefinition();                break;
            }  
   
            //
            // Rule 304:  using_declaration ::= using typename_opt dcolon_opt nested_name_specifier_opt unqualified_id_name ;
            //
            case 304: {       action.builder.
   consumeUsingDeclaration();                 break;
            }  
   
            //
            // Rule 305:  typename_opt ::= typename
            //
            case 305: {       action.builder.
   consumePlaceHolder();                 break;
            }  
   
            //
            // Rule 306:  typename_opt ::= $Empty
            //
            case 306: {       action.builder.
   consumeEmpty();                 break;
            }  
   
            //
            // Rule 307:  using_directive ::= using namespace dcolon_opt nested_name_specifier_opt namespace_name ;
            //
            case 307: {       action.builder.
   consumeUsingDirective();                 break;
            }  
   
            //
            // Rule 308:  asm_definition ::= asm ( stringlit ) ;
            //
            case 308: {       action.builder.
   consumeDeclarationASM();                break;
            }  
   
            //
            // Rule 309:  linkage_specification ::= extern stringlit { <openscope-ast> declaration_seq_opt }
            //
            case 309: {       action.builder.
   consumeLinkageSpecification();                 break;
            }  
   
            //
            // Rule 310:  linkage_specification ::= extern stringlit <openscope-ast> declaration
            //
            case 310: {       action.builder.
   consumeLinkageSpecification();                 break;
            }  
   
            //
            // Rule 316:  init_declarator ::= declarator initializer
            //
            case 316: {       action.builder.
   consumeDeclaratorWithInitializer(true);                 break;
            }  
   
            //
            // Rule 318:  declarator ::= <openscope-ast> ptr_operator_seq direct_declarator
            //
            case 318: {       action.builder.
   consumeDeclaratorWithPointer(true);                 break;
            }  
   
            //
            // Rule 320:  function_declarator ::= <openscope-ast> ptr_operator_seq direct_declarator
            //
            case 320: {       action.builder.
   consumeDeclaratorWithPointer(true);                 break;
            }  
   
            //
            // Rule 324:  basic_direct_declarator ::= declarator_id_name
            //
            case 324: {       action.builder.
   consumeDirectDeclaratorIdentifier();                 break;
            }  
   
            //
            // Rule 325:  basic_direct_declarator ::= ( declarator )
            //
            case 325: {       action.builder.
   consumeDirectDeclaratorBracketed();                 break;
            }  
   
            //
            // Rule 326:  function_direct_declarator ::= basic_direct_declarator ( <openscope-ast> parameter_declaration_clause ) <openscope-ast> cv_qualifier_seq_opt <openscope-ast> exception_specification_opt
            //
            case 326: {       action.builder.
   consumeDirectDeclaratorFunctionDeclarator(true);                 break;
            }  
   
            //
            // Rule 327:  array_direct_declarator ::= array_direct_declarator array_modifier
            //
            case 327: {       action.builder.
   consumeDirectDeclaratorArrayDeclarator(true);                 break;
            }  
   
            //
            // Rule 328:  array_direct_declarator ::= basic_direct_declarator array_modifier
            //
            case 328: {       action.builder.
   consumeDirectDeclaratorArrayDeclarator(true);                 break;
            }  
   
            //
            // Rule 329:  array_modifier ::= [ constant_expression ]
            //
            case 329: {       action.builder.
   consumeDirectDeclaratorArrayModifier(true);                 break;
            }  
   
            //
            // Rule 330:  array_modifier ::= [ ]
            //
            case 330: {       action.builder.
   consumeDirectDeclaratorArrayModifier(false);                 break;
            }  
   
            //
            // Rule 331:  ptr_operator ::= * <openscope-ast> cv_qualifier_seq_opt
            //
            case 331: {       action.builder.
   consumePointer();                 break;
            }  
   
            //
            // Rule 332:  ptr_operator ::= &
            //
            case 332: {       action.builder.
   consumeReferenceOperator();                 break;
            }  
   
            //
            // Rule 333:  ptr_operator ::= dcolon_opt nested_name_specifier * <openscope-ast> cv_qualifier_seq_opt
            //
            case 333: {       action.builder.
   consumePointerToMember();                 break;
            }  
   
            //
            // Rule 339:  cv_qualifier ::= const
            //
            case 339: {       action.builder.
   consumeDeclSpecToken();                break;
            }  
   
            //
            // Rule 340:  cv_qualifier ::= volatile
            //
            case 340: {       action.builder.
   consumeDeclSpecToken();                break;
            }  
   
            //
            // Rule 342:  declarator_id_name ::= dcolon_opt nested_name_specifier_opt type_name
            //
            case 342: {       action.builder.
   consumeQualifiedId(false);                 break;
            }  
   
            //
            // Rule 343:  type_id ::= type_specifier_seq
            //
            case 343: {       action.builder.
   consumeTypeId(false);                 break;
            }  
   
            //
            // Rule 344:  type_id ::= type_specifier_seq abstract_declarator
            //
            case 344: {       action.builder.
   consumeTypeId(true);                 break;
            }  
   
            //
            // Rule 347:  abstract_declarator ::= <openscope-ast> ptr_operator_seq
            //
            case 347: {       action.builder.
   consumeDeclaratorWithPointer(false);                 break;
            }  
   
            //
            // Rule 348:  abstract_declarator ::= <openscope-ast> ptr_operator_seq direct_abstract_declarator
            //
            case 348: {       action.builder.
   consumeDeclaratorWithPointer(true);                 break;
            }  
   
            //
            // Rule 352:  basic_direct_abstract_declarator ::= ( abstract_declarator )
            //
            case 352: {       action.builder.
   consumeDirectDeclaratorBracketed();                 break;
            }  
   
            //
            // Rule 353:  array_direct_abstract_declarator ::= array_modifier
            //
            case 353: {       action.builder.
   consumeDirectDeclaratorArrayDeclarator(false);                 break;
            }  
   
            //
            // Rule 354:  array_direct_abstract_declarator ::= array_direct_abstract_declarator array_modifier
            //
            case 354: {       action.builder.
   consumeDirectDeclaratorArrayDeclarator(true);                 break;
            }  
   
            //
            // Rule 355:  array_direct_abstract_declarator ::= basic_direct_abstract_declarator array_modifier
            //
            case 355: {       action.builder.
   consumeDirectDeclaratorArrayDeclarator(true);                 break;
            }  
   
            //
            // Rule 356:  function_direct_abstract_declarator ::= basic_direct_abstract_declarator ( <openscope-ast> parameter_declaration_clause ) <openscope-ast> cv_qualifier_seq_opt <openscope-ast> exception_specification_opt
            //
            case 356: {       action.builder.
   consumeDirectDeclaratorFunctionDeclarator(true);                 break;
            }  
   
            //
            // Rule 357:  function_direct_abstract_declarator ::= ( <openscope-ast> parameter_declaration_clause ) <openscope-ast> cv_qualifier_seq_opt <openscope-ast> exception_specification_opt
            //
            case 357: {       action.builder.
   consumeDirectDeclaratorFunctionDeclarator(false);                 break;
            }  
   
            //
            // Rule 358:  parameter_declaration_clause ::= parameter_declaration_list_opt ...
            //
            case 358: {       action.builder.
   consumePlaceHolder();                 break;
            }  
   
            //
            // Rule 359:  parameter_declaration_clause ::= parameter_declaration_list_opt
            //
            case 359: {       action.builder.
   consumeEmpty();                 break;
            }  
   
            //
            // Rule 360:  parameter_declaration_clause ::= parameter_declaration_list , ...
            //
            case 360: {       action.builder.
   consumePlaceHolder();                 break;
            }  
   
            //
            // Rule 366:  abstract_declarator_opt ::= $Empty
            //
            case 366: {       action.builder.
   consumeEmpty();                 break;
            }  
   
            //
            // Rule 367:  parameter_declaration ::= declaration_specifiers parameter_init_declarator
            //
            case 367: {       action.builder.
   consumeParameterDeclaration();                 break;
            }  
   
            //
            // Rule 368:  parameter_declaration ::= declaration_specifiers
            //
            case 368: {       action.builder.
   consumeParameterDeclarationWithoutDeclarator();                 break;
            }  
   
            //
            // Rule 370:  parameter_init_declarator ::= declarator = parameter_initializer
            //
            case 370: {       action.builder.
   consumeDeclaratorWithInitializer(true);                 break;
            }  
   
            //
            // Rule 372:  parameter_init_declarator ::= abstract_declarator = parameter_initializer
            //
            case 372: {       action.builder.
   consumeDeclaratorWithInitializer(true);                 break;
            }  
   
            //
            // Rule 373:  parameter_init_declarator ::= = parameter_initializer
            //
            case 373: {       action.builder.
   consumeDeclaratorWithInitializer(false);                 break;
            }  
   
            //
            // Rule 374:  parameter_initializer ::= assignment_expression
            //
            case 374: {       action.builder.
   consumeInitializer();                 break;
            }  
   
            //
            // Rule 375:  function_definition ::= declaration_specifiers_opt function_declarator <openscope-ast> ctor_initializer_list_opt function_body
            //
            case 375: {       action.builder.
   consumeFunctionDefinition(false);                 break;
            }  
   
            //
            // Rule 376:  function_definition ::= declaration_specifiers_opt function_declarator try <openscope-ast> ctor_initializer_list_opt function_body <openscope-ast> handler_seq
            //
            case 376: {       action.builder.
   consumeFunctionDefinition(true);                 break;
            }  
   
            //
            // Rule 379:  initializer ::= ( expression_list )
            //
            case 379: {       action.builder.
   consumeInitializerConstructor();                 break;
            }  
   
            //
            // Rule 380:  initializer_clause ::= assignment_expression
            //
            case 380: {       action.builder.
   consumeInitializer();                 break;
            }  
   
            //
            // Rule 381:  initializer_clause ::= { <openscope-ast> initializer_list , }
            //
            case 381: {       action.builder.
   consumeInitializerList();                 break;
            }  
   
            //
            // Rule 382:  initializer_clause ::= { <openscope-ast> initializer_list }
            //
            case 382: {       action.builder.
   consumeInitializerList();                 break;
            }  
   
            //
            // Rule 383:  initializer_clause ::= { <openscope-ast> }
            //
            case 383: {       action.builder.
   consumeInitializerList();                 break;
            }  
   
            //
            // Rule 388:  class_specifier ::= class_head { <openscope-ast> member_declaration_list_opt }
            //
            case 388: {       action.builder.
   consumeClassSpecifier();                 break;
            }  
   
            //
            // Rule 389:  class_head ::= class_keyword identifier_name_opt <openscope-ast> base_clause_opt
            //
            case 389: {       action.builder.
   consumeClassHead(false);                 break;
            }  
   
            //
            // Rule 390:  class_head ::= class_keyword template_id_name <openscope-ast> base_clause_opt
            //
            case 390: {       action.builder.
   consumeClassHead(false);                 break;
            }  
   
            //
            // Rule 391:  class_head ::= class_keyword nested_name_specifier identifier_name <openscope-ast> base_clause_opt
            //
            case 391: {       action.builder.
   consumeClassHead(true);                 break;
            }  
   
            //
            // Rule 392:  class_head ::= class_keyword nested_name_specifier template_id_name <openscope-ast> base_clause_opt
            //
            case 392: {       action.builder.
   consumeClassHead(true);                 break;
            }  
   
            //
            // Rule 396:  identifier_name_opt ::= $Empty
            //
            case 396: {       action.builder.
   consumeEmpty();                 break;
            } 
   
            //
            // Rule 400:  visibility_label ::= access_specifier_keyword :
            //
            case 400: {       action.builder.
   consumeVisibilityLabel();                 break;
            }  
   
            //
            // Rule 401:  member_declaration ::= declaration_specifiers_opt <openscope-ast> member_declarator_list ;
            //
            case 401: {       action.builder.
   consumeDeclarationSimple(true);                 break;
            }  
   
            //
            // Rule 402:  member_declaration ::= declaration_specifiers_opt ;
            //
            case 402: {       action.builder.
   consumeDeclarationSimple(false);                 break;
            }  
   
            //
            // Rule 405:  member_declaration ::= dcolon_opt nested_name_specifier template_opt unqualified_id_name ;
            //
            case 405: {       action.builder.
   consumeMemberDeclarationQualifiedId();                 break;
            }  
   
            //
            // Rule 409:  member_declaration ::= ERROR_TOKEN
            //
            case 409: {       action.builder.
   consumeDeclarationProblem();                 break;
            }  
   
            //
            // Rule 417:  member_declarator ::= declarator constant_initializer
            //
            case 417: {       action.builder.
   consumeMemberDeclaratorWithInitializer();                 break;
            }  
   
            //
            // Rule 418:  member_declarator ::= bit_field_declarator : constant_expression
            //
            case 418: {       action.builder.
   consumeBitField(true);                 break;
            }  
   
            //
            // Rule 419:  member_declarator ::= : constant_expression
            //
            case 419: {       action.builder.
   consumeBitField(false);                 break;
            }  
   
            //
            // Rule 420:  bit_field_declarator ::= identifier_name
            //
            case 420: {       action.builder.
   consumeDirectDeclaratorIdentifier();                 break;
            }  
   
            //
            // Rule 427:  base_specifier ::= dcolon_opt nested_name_specifier_opt class_name
            //
            case 427: {       action.builder.
   consumeBaseSpecifier(false);                 break;
            }  
   
            //
            // Rule 428:  base_specifier ::= virtual_opt access_specifier_keyword virtual_opt dcolon_opt nested_name_specifier_opt class_name
            //
            case 428: {       action.builder.
   consumeBaseSpecifier(true);                 break;
            }  
   
            //
            // Rule 429:  virtual_opt ::= virtual
            //
            case 429: {       action.builder.
   consumePlaceHolder();                 break;
            }  
   
            //
            // Rule 430:  virtual_opt ::= $Empty
            //
            case 430: {       action.builder.
   consumeEmpty();                 break;
            }  
   
            //
            // Rule 436:  conversion_function_id_name ::= operator conversion_type_id
            //
            case 436: {       action.builder.
   consumeConversionName();                break;
            }  
   
            //
            // Rule 437:  conversion_type_id ::= type_specifier_seq conversion_declarator
            //
            case 437: {       action.builder.
   consumeTypeId(true);                 break;
            }  
   
            //
            // Rule 438:  conversion_type_id ::= type_specifier_seq
            //
            case 438: {       action.builder.
   consumeTypeId(false);                 break;
            }  
   
            //
            // Rule 439:  conversion_declarator ::= <openscope-ast> ptr_operator_seq
            //
            case 439: {       action.builder.
   consumeDeclaratorWithPointer(false);                 break;
            }  
   
            //
            // Rule 445:  mem_initializer ::= mem_initializer_name ( expression_list_opt )
            //
            case 445: {       action.builder.
   consumeConstructorChainInitializer();                 break;
            }  
   
            //
            // Rule 446:  mem_initializer_name ::= dcolon_opt nested_name_specifier_opt class_name
            //
            case 446: {       action.builder.
   consumeQualifiedId(false);                 break;
            }  
   
            //
            // Rule 449:  operator_function_id_name ::= operator_id_name < <openscope-ast> template_argument_list_opt >
            //
            case 449: {       action.builder.
   consumeTemplateId();                 break;
            }  
   
            //
            // Rule 450:  operator_id_name ::= operator overloadable_operator
            //
            case 450: {       action.builder.
   consumeOperatorName();                 break;
            }  
   
            //
            // Rule 493:  template_declaration ::= export_opt template < <openscope-ast> template_parameter_list > declaration
            //
            case 493: {       action.builder.
   consumeTemplateDeclaration();                 break;
            }  
   
            //
            // Rule 494:  export_opt ::= export
            //
            case 494: {       action.builder.
   consumePlaceHolder();                 break;
            }  
   
            //
            // Rule 495:  export_opt ::= $Empty
            //
            case 495: {       action.builder.
   consumeEmpty();                 break;
            }  
   
            //
            // Rule 500:  type_parameter ::= class identifier_name_opt
            //
            case 500: {       action.builder.
   consumeSimpleTypeTemplateParameter(false);                 break;
            }  
   
            //
            // Rule 501:  type_parameter ::= class identifier_name_opt = type_id
            //
            case 501: {       action.builder.
   consumeSimpleTypeTemplateParameter(true);                 break;
            }  
   
            //
            // Rule 502:  type_parameter ::= typename identifier_name_opt
            //
            case 502: {       action.builder.
   consumeSimpleTypeTemplateParameter(false);                 break;
            }  
   
            //
            // Rule 503:  type_parameter ::= typename identifier_name_opt = type_id
            //
            case 503: {       action.builder.
   consumeSimpleTypeTemplateParameter(true);                 break;
            }  
   
            //
            // Rule 504:  type_parameter ::= template < <openscope-ast> template_parameter_list > class identifier_name_opt
            //
            case 504: {       action.builder.
   consumeTemplatedTypeTemplateParameter(false);                 break;
            }  
   
            //
            // Rule 505:  type_parameter ::= template < <openscope-ast> template_parameter_list > class identifier_name_opt = id_expression
            //
            case 505: {       action.builder.
   consumeTemplatedTypeTemplateParameter(true);                 break;
            }  
   
            //
            // Rule 506:  template_id_name ::= template_identifier < <openscope-ast> template_argument_list_opt >
            //
            case 506: {       action.builder.
   consumeTemplateId();                 break;
            }  
   
            //
            // Rule 515:  explicit_instantiation ::= template declaration
            //
            case 515: {       action.builder.
   consumeTemplateExplicitInstantiation();                 break;
            }  
   
            //
            // Rule 516:  explicit_specialization ::= template < > declaration
            //
            case 516: {       action.builder.
   consumeTemplateExplicitSpecialization();                 break;
            }  
   
            //
            // Rule 517:  try_block ::= try compound_statement <openscope-ast> handler_seq
            //
            case 517: {       action.builder.
   consumeStatementTryBlock();                 break;
            }  
   
            //
            // Rule 520:  handler ::= catch ( exception_declaration ) compound_statement
            //
            case 520: {       action.builder.
   consumeStatementCatchHandler(false);                 break;
            }  
   
            //
            // Rule 521:  handler ::= catch ( ... ) compound_statement
            //
            case 521: {       action.builder.
   consumeStatementCatchHandler(true);                 break;
            }  
   
            //
            // Rule 522:  exception_declaration ::= type_specifier_seq <openscope-ast> declarator
            //
            case 522: {       action.builder.
   consumeDeclarationSimple(true);                 break;
            }  
   
            //
            // Rule 523:  exception_declaration ::= type_specifier_seq <openscope-ast> abstract_declarator
            //
            case 523: {       action.builder.
   consumeDeclarationSimple(true);                 break;
            }  
   
            //
            // Rule 524:  exception_declaration ::= type_specifier_seq
            //
            case 524: {       action.builder.
   consumeDeclarationSimple(false);                 break;
            }  
   
            //
            // Rule 532:  no_cast_start ::= ERROR_TOKEN
            //
            case 532: {       action.builder.
   consumeExpressionProblem();                 break;
            }  

    
            default:
                break;
        }
        return;
    }
}

