/*******************************************************************************
* Copyright (c) 2006, 2008 IBM Corporation and others.
* All rights reserved. This program and the accompanying materials
* are made available under the terms of the Eclipse Public License v1.0
* which accompanies this distribution, and is available at
* http://www.eclipse.org/legal/epl-v10.html
*
* Contributors:
*     IBM Corporation - initial API and implementation
*********************************************************************************/

// This file was generated by LPG

package org.eclipse.cdt.internal.core.dom.lrparser.cpp;

import lpg.lpgjavaruntime.*;

import java.util.*;
import org.eclipse.cdt.core.dom.ast.*;
import org.eclipse.cdt.core.dom.lrparser.IParser;
import org.eclipse.cdt.core.dom.lrparser.IParserActionTokenProvider;
import org.eclipse.cdt.core.dom.lrparser.lpgextensions.FixedBacktrackingParser;

import org.eclipse.cdt.core.dom.lrparser.action.ITokenMap;
import org.eclipse.cdt.core.dom.lrparser.action.TokenMap;

import org.eclipse.cdt.core.dom.ast.cpp.*;
import org.eclipse.cdt.internal.core.dom.parser.cpp.CPPNodeFactory;
import org.eclipse.cdt.core.dom.lrparser.action.cpp.CPPBuildASTParserAction;

public class CPPTemplateTypeParameterParser extends PrsStream implements RuleAction , IParserActionTokenProvider, IParser   
{
    private static ParseTable prs = new CPPTemplateTypeParameterParserprs();
    private FixedBacktrackingParser btParser;

    public FixedBacktrackingParser getParser() { return btParser; }
    private void setResult(Object object) { btParser.setSym1(object); }
    public Object getRhsSym(int i) { return btParser.getSym(i); }

    public int getRhsTokenIndex(int i) { return btParser.getToken(i); }
    public IToken getRhsIToken(int i) { return super.getIToken(getRhsTokenIndex(i)); }
    
    public int getRhsFirstTokenIndex(int i) { return btParser.getFirstToken(i); }
    public IToken getRhsFirstIToken(int i) { return super.getIToken(getRhsFirstTokenIndex(i)); }

    public int getRhsLastTokenIndex(int i) { return btParser.getLastToken(i); }
    public IToken getRhsLastIToken(int i) { return super.getIToken(getRhsLastTokenIndex(i)); }

    public int getLeftSpan() { return btParser.getFirstToken(); }
    public IToken getLeftIToken()  { return super.getIToken(getLeftSpan()); }

    public int getRightSpan() { return btParser.getLastToken(); }
    public IToken getRightIToken() { return super.getIToken(getRightSpan()); }

    public int getRhsErrorTokenIndex(int i)
    {
        int index = btParser.getToken(i);
        IToken err = super.getIToken(index);
        return (err instanceof ErrorToken ? index : 0);
    }
    public ErrorToken getRhsErrorIToken(int i)
    {
        int index = btParser.getToken(i);
        IToken err = super.getIToken(index);
        return (ErrorToken) (err instanceof ErrorToken ? err : null);
    }

    public CPPTemplateTypeParameterParser(LexStream lexStream)
    {
        super(lexStream);

        try
        {
            super.remapTerminalSymbols(orderedTerminalSymbols(), CPPTemplateTypeParameterParserprs.EOFT_SYMBOL);
        }
        catch(NullExportedSymbolsException e) {
        }
        catch(NullTerminalSymbolsException e) {
        }
        catch(UnimplementedTerminalsException e)
        {
            java.util.ArrayList unimplemented_symbols = e.getSymbols();
            System.out.println("The Lexer will not scan the following token(s):");
            for (int i = 0; i < unimplemented_symbols.size(); i++)
            {
                Integer id = (Integer) unimplemented_symbols.get(i);
                System.out.println("    " + CPPTemplateTypeParameterParsersym.orderedTerminalSymbols[id.intValue()]);               
            }
            System.out.println();                        
        }
        catch(UndefinedEofSymbolException e)
        {
            throw new Error(new UndefinedEofSymbolException
                                ("The Lexer does not implement the Eof symbol " +
                                 CPPTemplateTypeParameterParsersym.orderedTerminalSymbols[CPPTemplateTypeParameterParserprs.EOFT_SYMBOL]));
        } 
    }

    public String[] orderedTerminalSymbols() { return CPPTemplateTypeParameterParsersym.orderedTerminalSymbols; }
    public String getTokenKindName(int kind) { return CPPTemplateTypeParameterParsersym.orderedTerminalSymbols[kind]; }
    public int getEOFTokenKind() { return CPPTemplateTypeParameterParserprs.EOFT_SYMBOL; }
    public PrsStream getParseStream() { return (PrsStream) this; }
    
    //
    // Report error message for given error_token.
    //
    public final void reportErrorTokenMessage(int error_token, String msg)
    {
        int firsttok = super.getFirstErrorToken(error_token),
            lasttok = super.getLastErrorToken(error_token);
        String location = super.getFileName() + ':' +
                          (firsttok > lasttok
                                    ? (super.getEndLine(lasttok) + ":" + super.getEndColumn(lasttok))
                                    : (super.getLine(error_token) + ":" +
                                       super.getColumn(error_token) + ":" +
                                       super.getEndLine(error_token) + ":" +
                                       super.getEndColumn(error_token)))
                          + ": ";
        super.reportError((firsttok > lasttok ? ParseErrorCodes.INSERTION_CODE : ParseErrorCodes.SUBSTITUTION_CODE), location, msg);
    }

    public Object parser()
    {
        return parser(null, 0);
    }
    
    public Object parser(Monitor monitor)
    {
        return parser(monitor, 0);
    }
    
    public Object parser(int error_repair_count)
    {
        return parser(null, error_repair_count);
    }

    public Object parser(Monitor monitor, int error_repair_count)
    {
        try
        {
            btParser = new FixedBacktrackingParser(monitor, (TokenStream) this, prs, (RuleAction) this);
        }
        catch (NotBacktrackParseTableException e)
        {
            throw new Error(new NotBacktrackParseTableException
                                ("Regenerate CPPTemplateTypeParameterParserprs.java with -BACKTRACK option"));
        }
        catch (BadParseSymFileException e)
        {
            throw new Error(new BadParseSymFileException("Bad Parser Symbol File -- CPPTemplateTypeParameterParsersym.java"));
        }

        try
        {
            return (Object) btParser.parse(error_repair_count);
        }
        catch (BadParseException e)
        {
            reset(e.error_token); // point to error token
            DiagnoseParser diagnoseParser = new DiagnoseParser(this, prs);
            diagnoseParser.diagnose(e.error_token);
        }

        return null;
    }


private  CPPBuildASTParserAction  action;

public CPPTemplateTypeParameterParser() {  // constructor
}

private void initActions(IASTTranslationUnit tu, Set<IParser.Options> options) {
	action = new  CPPBuildASTParserAction ( CPPNodeFactory.getDefault() , this, tu);
	action.setParserOptions(options);
}


public void addToken(IToken token) {
	token.setKind(mapKind(token.getKind())); // TODO does mapKind need to be called?
	super.addToken(token);
}


public IASTCompletionNode parse(IASTTranslationUnit tu, Set<IParser.Options> options) {
	// this has to be done, or... kaboom!
	setStreamLength(getSize());
	initActions(tu, options);
	
	final int errorRepairCount = -1;  // -1 means full error handling
	parser(null, errorRepairCount); // do the actual parse
	super.resetTokenStream(); // allow tokens to be garbage collected

	// the completion node may be null
	IASTCompletionNode compNode = action.getASTCompletionNode();

	//action = null;
	//parserAction = null;
	return compNode;
}

// uncomment this method to use with backtracking parser
public List getRuleTokens() {
    return Collections.unmodifiableList(getTokens().subList(getLeftSpan(), getRightSpan() + 1));
}


public IASTNode getSecondaryParseResult() {
	return  action.getSecondaryParseResult();
}

public String[] getOrderedTerminalSymbols() {
	return CPPTemplateTypeParameterParsersym.orderedTerminalSymbols;
}

@SuppressWarnings("nls")
public String getName() {
	return "CPPTemplateTypeParameterParser";
}



private ITokenMap tokenMap = null;

public void setTokens(List<IToken> tokens) {
	resetTokenStream();
	addToken(new Token(null, 0, 0, 0)); // dummy token
	for(IToken token : tokens) {
		token.setKind(tokenMap.mapKind(token.getKind()));
		addToken(token);
	}
	addToken(new Token(null, 0, 0, CPPTemplateTypeParameterParsersym.TK_EOF_TOKEN));
}

public CPPTemplateTypeParameterParser(String[] mapFrom) {  // constructor
	tokenMap = new TokenMap(CPPTemplateTypeParameterParsersym.orderedTerminalSymbols, mapFrom);
}	



    public void ruleAction(int ruleNumber)
    {
        switch (ruleNumber)
        {
  
            //
            // Rule 1:  <openscope-ast> ::= $Empty
            //
            case 1: { action.   openASTScope();             break;
            }  
  
            //
            // Rule 2:  <empty> ::= $Empty
            //
            case 2: { action.   consumeEmpty();             break;
            }  
  
            //
            // Rule 13:  translation_unit ::= declaration_seq_opt
            //
            case 13: { action.   consumeTranslationUnit();            break;
            }  
  
            //
            // Rule 16:  literal ::= integer
            //
            case 16: { action.   consumeExpressionLiteral(ICPPASTLiteralExpression.lk_integer_constant);            break;
            }  
  
            //
            // Rule 17:  literal ::= 0
            //
            case 17: { action.   consumeExpressionLiteral(ICPPASTLiteralExpression.lk_integer_constant);            break;
            }  
  
            //
            // Rule 18:  literal ::= floating
            //
            case 18: { action.   consumeExpressionLiteral(ICPPASTLiteralExpression.lk_float_constant);            break;
            }  
  
            //
            // Rule 19:  literal ::= charconst
            //
            case 19: { action.   consumeExpressionLiteral(ICPPASTLiteralExpression.lk_char_constant);            break;
            }  
  
            //
            // Rule 20:  literal ::= stringlit
            //
            case 20: { action.   consumeExpressionLiteral(ICPPASTLiteralExpression.lk_string_literal);            break;
            }  
  
            //
            // Rule 21:  literal ::= true
            //
            case 21: { action.   consumeExpressionLiteral(ICPPASTLiteralExpression.lk_true);            break;
            }  
  
            //
            // Rule 22:  literal ::= false
            //
            case 22: { action.   consumeExpressionLiteral(ICPPASTLiteralExpression.lk_false);            break;
            }  
  
            //
            // Rule 23:  literal ::= this
            //
            case 23: { action.   consumeExpressionLiteral(ICPPASTLiteralExpression.lk_this);            break;
            }  
  
            //
            // Rule 25:  primary_expression ::= ( expression )
            //
            case 25: { action.   consumeExpressionBracketed();             break;
            }  
  
            //
            // Rule 27:  id_expression ::= qualified_or_unqualified_name
            //
            case 27: { action.   consumeExpressionName();             break;
            }  
  
            //
            // Rule 34:  unqualified_id_name ::= ~ identifier_token
            //
            case 34: { action.   consumeDestructorName();             break;
            }  
  
            //
            // Rule 35:  unqualified_id_name ::= ~ template_id_name
            //
            case 35: { action.   consumeDestructorNameTemplateId();             break;
            }  
  
            //
            // Rule 36:  identifier_name ::= identifier_token
            //
            case 36: { action.   consumeIdentifierName();             break;
            }  
  
            //
            // Rule 37:  template_opt ::= template
            //
            case 37: { action.   consumePlaceHolder();             break;
            }  
  
            //
            // Rule 38:  template_opt ::= $Empty
            //
            case 38: { action.   consumeEmpty();             break;
            }  
  
            //
            // Rule 39:  dcolon_opt ::= ::
            //
            case 39: { action.   consumeToken();             break;
            }  
  
            //
            // Rule 40:  dcolon_opt ::= $Empty
            //
            case 40: { action.   consumeEmpty();             break;
            }  
  
            //
            // Rule 41:  qualified_id_name ::= dcolon_opt nested_name_specifier template_opt unqualified_id_name
            //
            case 41: { action.   consumeQualifiedId(true);             break;
            }  
  
            //
            // Rule 42:  qualified_id_name ::= :: unqualified_id_name
            //
            case 42: { action.   consumeGlobalQualifiedId();             break;
            }  
  
            //
            // Rule 43:  nested_name_specifier ::= class_or_namespace_name :: nested_name_specifier_with_template
            //
            case 43: { action.   consumeNestedNameSpecifier(true);             break;
            }  
  
            //
            // Rule 44:  nested_name_specifier ::= class_or_namespace_name ::
            //
            case 44: { action.   consumeNestedNameSpecifier(false);             break;
            }  
  
            //
            // Rule 45:  nested_name_specifier_with_template ::= class_or_namespace_name_with_template :: nested_name_specifier_with_template
            //
            case 45: { action.   consumeNestedNameSpecifier(true);             break;
            }  
  
            //
            // Rule 46:  nested_name_specifier_with_template ::= class_or_namespace_name_with_template ::
            //
            case 46: { action.   consumeNestedNameSpecifier(false);             break;
            }  
  
            //
            // Rule 47:  class_or_namespace_name_with_template ::= template_opt class_or_namespace_name
            //
            case 47: { action.   consumeNameWithTemplateKeyword();             break;
            }  
  
            //
            // Rule 49:  nested_name_specifier_opt ::= $Empty
            //
            case 49: { action.   consumeNestedNameSpecifierEmpty();             break;
            }  
  
            //
            // Rule 52:  postfix_expression ::= postfix_expression [ expression ]
            //
            case 52: { action.   consumeExpressionArraySubscript();             break;
            }  
  
            //
            // Rule 53:  postfix_expression ::= postfix_expression ( expression_list_opt )
            //
            case 53: { action.   consumeExpressionFunctionCall();             break;
            }  
  
            //
            // Rule 54:  postfix_expression ::= simple_type_specifier ( expression_list_opt )
            //
            case 54: { action.   consumeExpressionSimpleTypeConstructor();            break;
            }  
  
            //
            // Rule 55:  postfix_expression ::= typename dcolon_opt nested_name_specifier <empty> identifier_name ( expression_list_opt )
            //
            case 55: { action.   consumeExpressionTypeName();            break;
            }  
  
            //
            // Rule 56:  postfix_expression ::= typename dcolon_opt nested_name_specifier template_opt template_id_name ( expression_list_opt )
            //
            case 56: { action.   consumeExpressionTypeName();            break;
            }  
  
            //
            // Rule 57:  postfix_expression ::= postfix_expression . qualified_or_unqualified_name
            //
            case 57: { action.   consumeExpressionFieldReference(false, false);             break;
            }  
  
            //
            // Rule 58:  postfix_expression ::= postfix_expression -> qualified_or_unqualified_name
            //
            case 58: { action.   consumeExpressionFieldReference(true, false);             break;
            }  
  
            //
            // Rule 59:  postfix_expression ::= postfix_expression . template qualified_or_unqualified_name
            //
            case 59: { action.   consumeExpressionFieldReference(false, true);             break;
            }  
  
            //
            // Rule 60:  postfix_expression ::= postfix_expression -> template qualified_or_unqualified_name
            //
            case 60: { action.   consumeExpressionFieldReference(true, true);             break;
            }  
  
            //
            // Rule 61:  postfix_expression ::= postfix_expression . pseudo_destructor_name
            //
            case 61: { action.   consumeExpressionFieldReference(false, false);             break;
            }  
  
            //
            // Rule 62:  postfix_expression ::= postfix_expression -> pseudo_destructor_name
            //
            case 62: { action.   consumeExpressionFieldReference(true, false);             break;
            }  
  
            //
            // Rule 63:  postfix_expression ::= postfix_expression ++
            //
            case 63: { action.   consumeExpressionUnaryOperator(IASTUnaryExpression.op_postFixIncr);             break;
            }  
  
            //
            // Rule 64:  postfix_expression ::= postfix_expression --
            //
            case 64: { action.   consumeExpressionUnaryOperator(IASTUnaryExpression.op_postFixDecr);             break;
            }  
  
            //
            // Rule 65:  postfix_expression ::= dynamic_cast < type_id > ( expression )
            //
            case 65: { action.   consumeExpressionCast(ICPPASTCastExpression.op_dynamic_cast);             break;
            }  
  
            //
            // Rule 66:  postfix_expression ::= static_cast < type_id > ( expression )
            //
            case 66: { action.   consumeExpressionCast(ICPPASTCastExpression.op_static_cast);             break;
            }  
  
            //
            // Rule 67:  postfix_expression ::= reinterpret_cast < type_id > ( expression )
            //
            case 67: { action.   consumeExpressionCast(ICPPASTCastExpression.op_reinterpret_cast);             break;
            }  
  
            //
            // Rule 68:  postfix_expression ::= const_cast < type_id > ( expression )
            //
            case 68: { action.   consumeExpressionCast(ICPPASTCastExpression.op_const_cast);             break;
            }  
  
            //
            // Rule 69:  postfix_expression ::= typeid ( expression )
            //
            case 69: { action.   consumeExpressionUnaryOperator(ICPPASTUnaryExpression.op_typeid);             break;
            }  
  
            //
            // Rule 70:  postfix_expression ::= typeid ( type_id )
            //
            case 70: { action.   consumeExpressionTypeId(ICPPASTTypeIdExpression.op_typeid);            break;
            }  
  
            //
            // Rule 71:  pseudo_destructor_name ::= dcolon_opt nested_name_specifier_opt type_name :: destructor_type_name
            //
            case 71: { action.   consumePsudoDestructorName(true);             break;
            }  
  
            //
            // Rule 72:  pseudo_destructor_name ::= dcolon_opt nested_name_specifier template template_id_name :: destructor_type_name
            //
            case 72: { action.   consumePsudoDestructorName(true);             break;
            }  
  
            //
            // Rule 73:  pseudo_destructor_name ::= dcolon_opt nested_name_specifier_opt destructor_type_name
            //
            case 73: { action.   consumePsudoDestructorName(false);             break;
            }  
  
            //
            // Rule 74:  destructor_type_name ::= ~ identifier_token
            //
            case 74: { action.   consumeDestructorName();             break;
            }  
  
            //
            // Rule 75:  destructor_type_name ::= ~ template_id_name
            //
            case 75: { action.   consumeDestructorNameTemplateId();             break;
            }  
  
            //
            // Rule 79:  unary_expression ::= ++ cast_expression
            //
            case 79: { action.   consumeExpressionUnaryOperator(IASTUnaryExpression.op_prefixIncr);             break;
            }  
  
            //
            // Rule 80:  unary_expression ::= -- cast_expression
            //
            case 80: { action.   consumeExpressionUnaryOperator(IASTUnaryExpression.op_prefixDecr);             break;
            }  
  
            //
            // Rule 81:  unary_expression ::= & cast_expression
            //
            case 81: { action.   consumeExpressionUnaryOperator(IASTUnaryExpression.op_amper);             break;
            }  
  
            //
            // Rule 82:  unary_expression ::= * cast_expression
            //
            case 82: { action.   consumeExpressionUnaryOperator(IASTUnaryExpression.op_star);             break;
            }  
  
            //
            // Rule 83:  unary_expression ::= + cast_expression
            //
            case 83: { action.   consumeExpressionUnaryOperator(IASTUnaryExpression.op_plus);             break;
            }  
  
            //
            // Rule 84:  unary_expression ::= - cast_expression
            //
            case 84: { action.   consumeExpressionUnaryOperator(IASTUnaryExpression.op_minus);             break;
            }  
  
            //
            // Rule 85:  unary_expression ::= ~ cast_expression
            //
            case 85: { action.   consumeExpressionUnaryOperator(IASTUnaryExpression.op_tilde);             break;
            }  
  
            //
            // Rule 86:  unary_expression ::= ! cast_expression
            //
            case 86: { action.   consumeExpressionUnaryOperator(IASTUnaryExpression.op_not);             break;
            }  
  
            //
            // Rule 87:  unary_expression ::= sizeof unary_expression
            //
            case 87: { action.   consumeExpressionUnaryOperator(IASTUnaryExpression.op_sizeof);             break;
            }  
  
            //
            // Rule 88:  unary_expression ::= sizeof ( type_id )
            //
            case 88: { action.   consumeExpressionTypeId(ICPPASTTypeIdExpression.op_sizeof);            break;
            }  
  
            //
            // Rule 89:  new_expression ::= dcolon_opt new new_placement_opt new_type_id <openscope-ast> new_array_expressions_opt new_initializer_opt
            //
            case 89: { action.   consumeExpressionNew(true);             break;
            }  
  
            //
            // Rule 90:  new_expression ::= dcolon_opt new new_placement_opt ( type_id ) <openscope-ast> new_array_expressions_opt new_initializer_opt
            //
            case 90: { action.   consumeExpressionNew(false);             break;
            }  
  
            //
            // Rule 92:  new_placement_opt ::= $Empty
            //
            case 92: { action.   consumeEmpty();             break;
            }  
  
            //
            // Rule 93:  new_type_id ::= type_specifier_seq
            //
            case 93: { action.   consumeTypeId(false);             break;
            }  
  
            //
            // Rule 94:  new_type_id ::= type_specifier_seq new_declarator
            //
            case 94: { action.   consumeTypeId(true);             break;
            }  
  
            //
            // Rule 95:  new_declarator ::= <openscope-ast> new_pointer_operators
            //
            case 95: { action.   consumeNewDeclarator();            break;
            }  
  
            //
            // Rule 102:  new_initializer ::= ( expression_list_opt )
            //
            case 102: { action.   consumeNewInitializer();             break;
            }  
  
            //
            // Rule 104:  new_initializer_opt ::= $Empty
            //
            case 104: { action.   consumeEmpty();             break;
            }  
  
            //
            // Rule 105:  delete_expression ::= dcolon_opt delete cast_expression
            //
            case 105: { action.   consumeExpressionDelete(false);             break;
            }  
  
            //
            // Rule 106:  delete_expression ::= dcolon_opt delete [ ] cast_expression
            //
            case 106: { action.   consumeExpressionDelete(true);             break;
            }  
  
            //
            // Rule 108:  cast_expression ::= ( type_id ) cast_expression
            //
            case 108: { action.   consumeExpressionCast(ICPPASTCastExpression.op_cast);             break;
            }  
  
            //
            // Rule 110:  pm_expression ::= pm_expression .* cast_expression
            //
            case 110: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_pmdot);             break;
            }  
  
            //
            // Rule 111:  pm_expression ::= pm_expression ->* cast_expression
            //
            case 111: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_pmarrow);             break;
            }  
  
            //
            // Rule 113:  multiplicative_expression ::= multiplicative_expression * pm_expression
            //
            case 113: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_multiply);             break;
            }  
  
            //
            // Rule 114:  multiplicative_expression ::= multiplicative_expression / pm_expression
            //
            case 114: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_divide);             break;
            }  
  
            //
            // Rule 115:  multiplicative_expression ::= multiplicative_expression % pm_expression
            //
            case 115: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_modulo);             break;
            }  
  
            //
            // Rule 117:  additive_expression ::= additive_expression + multiplicative_expression
            //
            case 117: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_plus);             break;
            }  
  
            //
            // Rule 118:  additive_expression ::= additive_expression - multiplicative_expression
            //
            case 118: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_minus);             break;
            }  
  
            //
            // Rule 120:  shift_expression ::= shift_expression << additive_expression
            //
            case 120: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_shiftLeft);             break;
            }  
  
            //
            // Rule 121:  shift_expression ::= shift_expression >> additive_expression
            //
            case 121: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_shiftRight);             break;
            }  
  
            //
            // Rule 123:  relational_expression ::= relational_expression < shift_expression
            //
            case 123: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_lessThan);             break;
            }  
  
            //
            // Rule 124:  relational_expression ::= relational_expression > shift_expression
            //
            case 124: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_greaterThan);             break;
            }  
  
            //
            // Rule 125:  relational_expression ::= relational_expression <= shift_expression
            //
            case 125: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_lessEqual);             break;
            }  
  
            //
            // Rule 126:  relational_expression ::= relational_expression >= shift_expression
            //
            case 126: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_greaterEqual);             break;
            }  
  
            //
            // Rule 128:  equality_expression ::= equality_expression == relational_expression
            //
            case 128: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_equals);             break;
            }  
  
            //
            // Rule 129:  equality_expression ::= equality_expression != relational_expression
            //
            case 129: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_notequals);             break;
            }  
  
            //
            // Rule 131:  and_expression ::= and_expression & equality_expression
            //
            case 131: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_binaryAnd);             break;
            }  
  
            //
            // Rule 133:  exclusive_or_expression ::= exclusive_or_expression ^ and_expression
            //
            case 133: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_binaryXor);             break;
            }  
  
            //
            // Rule 135:  inclusive_or_expression ::= inclusive_or_expression | exclusive_or_expression
            //
            case 135: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_binaryOr);             break;
            }  
  
            //
            // Rule 137:  logical_and_expression ::= logical_and_expression && inclusive_or_expression
            //
            case 137: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_logicalAnd);             break;
            }  
  
            //
            // Rule 139:  logical_or_expression ::= logical_or_expression || logical_and_expression
            //
            case 139: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_logicalOr);             break;
            }  
  
            //
            // Rule 141:  conditional_expression ::= logical_or_expression ? expression : assignment_expression
            //
            case 141: { action.   consumeExpressionConditional();             break;
            }  
  
            //
            // Rule 142:  throw_expression ::= throw
            //
            case 142: { action.   consumeExpressionThrow(false);             break;
            }  
  
            //
            // Rule 143:  throw_expression ::= throw assignment_expression
            //
            case 143: { action.   consumeExpressionThrow(true);             break;
            }  
  
            //
            // Rule 146:  assignment_expression ::= logical_or_expression = assignment_expression
            //
            case 146: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_assign);             break;
            }  
  
            //
            // Rule 147:  assignment_expression ::= logical_or_expression *= assignment_expression
            //
            case 147: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_multiplyAssign);             break;
            }  
  
            //
            // Rule 148:  assignment_expression ::= logical_or_expression /= assignment_expression
            //
            case 148: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_divideAssign);             break;
            }  
  
            //
            // Rule 149:  assignment_expression ::= logical_or_expression %= assignment_expression
            //
            case 149: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_moduloAssign);             break;
            }  
  
            //
            // Rule 150:  assignment_expression ::= logical_or_expression += assignment_expression
            //
            case 150: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_plusAssign);             break;
            }  
  
            //
            // Rule 151:  assignment_expression ::= logical_or_expression -= assignment_expression
            //
            case 151: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_minusAssign);             break;
            }  
  
            //
            // Rule 152:  assignment_expression ::= logical_or_expression >>= assignment_expression
            //
            case 152: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_shiftRightAssign);             break;
            }  
  
            //
            // Rule 153:  assignment_expression ::= logical_or_expression <<= assignment_expression
            //
            case 153: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_shiftLeftAssign);             break;
            }  
  
            //
            // Rule 154:  assignment_expression ::= logical_or_expression &= assignment_expression
            //
            case 154: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_binaryAndAssign);             break;
            }  
  
            //
            // Rule 155:  assignment_expression ::= logical_or_expression ^= assignment_expression
            //
            case 155: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_binaryXorAssign);             break;
            }  
  
            //
            // Rule 156:  assignment_expression ::= logical_or_expression |= assignment_expression
            //
            case 156: { action.   consumeExpressionBinaryOperator(ICPPASTBinaryExpression.op_binaryOrAssign);             break;
            }  
  
            //
            // Rule 158:  expression_list ::= <openscope-ast> expression_list_actual
            //
            case 158: { action.   consumeExpressionList();             break;
            }  
  
            //
            // Rule 162:  expression_list_opt ::= $Empty
            //
            case 162: { action.   consumeEmpty();             break;
            }  
  
            //
            // Rule 164:  expression_opt ::= $Empty
            //
            case 164: { action.   consumeEmpty();             break;
            }  
  
            //
            // Rule 167:  constant_expression_opt ::= $Empty
            //
            case 167: { action.   consumeEmpty();             break;
            }  
  
            //
            // Rule 176:  statement ::= ERROR_TOKEN
            //
            case 176: { action.   consumeStatementProblem();             break;
            }  
  
            //
            // Rule 177:  labeled_statement ::= identifier : statement
            //
            case 177: { action.   consumeStatementLabeled();             break;
            }  
  
            //
            // Rule 178:  labeled_statement ::= case constant_expression : statement
            //
            case 178: { action.   consumeStatementCase();             break;
            }  
  
            //
            // Rule 179:  labeled_statement ::= default : statement
            //
            case 179: { action.   consumeStatementDefault();             break;
            }  
  
            //
            // Rule 180:  expression_statement ::= expression ;
            //
            case 180: { action.   consumeStatementExpression();             break;
            }  
  
            //
            // Rule 181:  expression_statement ::= ;
            //
            case 181: { action.   consumeStatementNull();             break;
            }  
  
            //
            // Rule 182:  compound_statement ::= { <openscope-ast> statement_seq }
            //
            case 182: { action.   consumeStatementCompoundStatement(true);             break;
            }  
  
            //
            // Rule 183:  compound_statement ::= { }
            //
            case 183: { action.   consumeStatementCompoundStatement(false);             break;
            }  
  
            //
            // Rule 186:  selection_statement ::= if ( condition ) statement
            //
            case 186: { action.   consumeStatementIf(false);             break;
            }  
  
            //
            // Rule 187:  selection_statement ::= if ( condition ) statement else statement
            //
            case 187: { action.   consumeStatementIf(true);             break;
            }  
  
            //
            // Rule 188:  selection_statement ::= switch ( condition ) statement
            //
            case 188: { action.   consumeStatementSwitch();             break;
            }  
  
            //
            // Rule 190:  condition ::= type_specifier_seq declarator = assignment_expression
            //
            case 190: { action.   consumeConditionDeclaration();             break;
            }  
  
            //
            // Rule 192:  condition_opt ::= $Empty
            //
            case 192: { action.   consumeEmpty();            break;
            }  
  
            //
            // Rule 193:  iteration_statement ::= while ( condition ) statement
            //
            case 193: { action.   consumeStatementWhileLoop();             break;
            }  
  
            //
            // Rule 194:  iteration_statement ::= do statement while ( expression ) ;
            //
            case 194: { action.   consumeStatementDoLoop();             break;
            }  
  
            //
            // Rule 195:  iteration_statement ::= for ( for_init_statement condition_opt ; expression_opt ) statement
            //
            case 195: { action.  consumeStatementForLoop();            break;
            }  
  
            //
            // Rule 197:  for_init_statement ::= simple_declaration_with_declspec
            //
            case 197: { action.   consumeStatementDeclaration();             break;
            }  
  
            //
            // Rule 198:  jump_statement ::= break ;
            //
            case 198: { action.   consumeStatementBreak();             break;
            }  
  
            //
            // Rule 199:  jump_statement ::= continue ;
            //
            case 199: { action.   consumeStatementContinue();             break;
            }  
  
            //
            // Rule 200:  jump_statement ::= return expression ;
            //
            case 200: { action.   consumeStatementReturn(true);             break;
            }  
  
            //
            // Rule 201:  jump_statement ::= return ;
            //
            case 201: { action.   consumeStatementReturn(false);             break;
            }  
  
            //
            // Rule 202:  jump_statement ::= goto identifier_token ;
            //
            case 202: { action.   consumeStatementGoto();             break;
            }  
  
            //
            // Rule 203:  declaration_statement ::= block_declaration
            //
            case 203: { action.   consumeStatementDeclarationWithDisambiguation();             break;
            }  
  
            //
            // Rule 204:  declaration_statement ::= function_definition
            //
            case 204: { action.   consumeStatementDeclaration();             break;
            }  
  
            //
            // Rule 212:  declaration ::= ERROR_TOKEN
            //
            case 212: { action.   consumeDeclarationProblem();             break;
            }  
  
            //
            // Rule 222:  simple_declaration ::= declaration_specifiers_opt <openscope-ast> init_declarator_list_opt ;
            //
            case 222: { action.   consumeDeclarationSimple(true);             break;
            }  
  
            //
            // Rule 223:  simple_declaration_with_declspec ::= declaration_specifiers <openscope-ast> init_declarator_list_opt ;
            //
            case 223: { action.   consumeDeclarationSimple(true);             break;
            }  
  
            //
            // Rule 224:  declaration_specifiers ::= <openscope-ast> simple_declaration_specifiers
            //
            case 224: { action.   consumeDeclarationSpecifiersSimple();             break;
            }  
  
            //
            // Rule 225:  declaration_specifiers ::= <openscope-ast> class_declaration_specifiers
            //
            case 225: { action.   consumeDeclarationSpecifiersComposite();             break;
            }  
  
            //
            // Rule 226:  declaration_specifiers ::= <openscope-ast> elaborated_declaration_specifiers
            //
            case 226: { action.   consumeDeclarationSpecifiersComposite();             break;
            }  
  
            //
            // Rule 227:  declaration_specifiers ::= <openscope-ast> enum_declaration_specifiers
            //
            case 227: { action.   consumeDeclarationSpecifiersComposite();             break;
            }  
  
            //
            // Rule 228:  declaration_specifiers ::= <openscope-ast> type_name_declaration_specifiers
            //
            case 228: { action.   consumeDeclarationSpecifiersTypeName();             break;
            }  
  
            //
            // Rule 230:  declaration_specifiers_opt ::= $Empty
            //
            case 230: { action.   consumeEmpty();             break;
            }  
  
            //
            // Rule 234:  no_type_declaration_specifier ::= friend
            //
            case 234: { action.   consumeDeclSpecToken();            break;
            }  
  
            //
            // Rule 235:  no_type_declaration_specifier ::= typedef
            //
            case 235: { action.   consumeDeclSpecToken();            break;
            }  
  
            //
            // Rule 255:  storage_class_specifier ::= auto
            //
            case 255: { action.   consumeDeclSpecToken();            break;
            }  
  
            //
            // Rule 256:  storage_class_specifier ::= register
            //
            case 256: { action.   consumeDeclSpecToken();            break;
            }  
  
            //
            // Rule 257:  storage_class_specifier ::= static
            //
            case 257: { action.   consumeDeclSpecToken();            break;
            }  
  
            //
            // Rule 258:  storage_class_specifier ::= extern
            //
            case 258: { action.   consumeDeclSpecToken();            break;
            }  
  
            //
            // Rule 259:  storage_class_specifier ::= mutable
            //
            case 259: { action.   consumeDeclSpecToken();            break;
            }  
  
            //
            // Rule 260:  function_specifier ::= inline
            //
            case 260: { action.   consumeDeclSpecToken();            break;
            }  
  
            //
            // Rule 261:  function_specifier ::= virtual
            //
            case 261: { action.   consumeDeclSpecToken();            break;
            }  
  
            //
            // Rule 262:  function_specifier ::= explicit
            //
            case 262: { action.   consumeDeclSpecToken();            break;
            }  
  
            //
            // Rule 263:  simple_type_specifier ::= char
            //
            case 263: { action.   consumeDeclSpecToken();            break;
            }  
  
            //
            // Rule 264:  simple_type_specifier ::= wchar_t
            //
            case 264: { action.   consumeDeclSpecToken();            break;
            }  
  
            //
            // Rule 265:  simple_type_specifier ::= bool
            //
            case 265: { action.   consumeDeclSpecToken();            break;
            }  
  
            //
            // Rule 266:  simple_type_specifier ::= short
            //
            case 266: { action.   consumeDeclSpecToken();            break;
            }  
  
            //
            // Rule 267:  simple_type_specifier ::= int
            //
            case 267: { action.   consumeDeclSpecToken();            break;
            }  
  
            //
            // Rule 268:  simple_type_specifier ::= long
            //
            case 268: { action.   consumeDeclSpecToken();            break;
            }  
  
            //
            // Rule 269:  simple_type_specifier ::= signed
            //
            case 269: { action.   consumeDeclSpecToken();            break;
            }  
  
            //
            // Rule 270:  simple_type_specifier ::= unsigned
            //
            case 270: { action.   consumeDeclSpecToken();            break;
            }  
  
            //
            // Rule 271:  simple_type_specifier ::= float
            //
            case 271: { action.   consumeDeclSpecToken();            break;
            }  
  
            //
            // Rule 272:  simple_type_specifier ::= double
            //
            case 272: { action.   consumeDeclSpecToken();            break;
            }  
  
            //
            // Rule 273:  simple_type_specifier ::= void
            //
            case 273: { action.   consumeDeclSpecToken();            break;
            }  
  
            //
            // Rule 276:  type_name_specifier ::= dcolon_opt nested_name_specifier_opt type_name
            //
            case 276: { action.   consumeQualifiedId(false);             break;
            }  
  
            //
            // Rule 277:  type_name_specifier ::= dcolon_opt nested_name_specifier template template_id_name
            //
            case 277: { action.   consumeQualifiedId(false);             break;
            }  
  
            //
            // Rule 278:  type_name_specifier ::= typename dcolon_opt nested_name_specifier identifier_name
            //
            case 278: { action.   consumeQualifiedId(false);             break;
            }  
  
            //
            // Rule 279:  type_name_specifier ::= typename dcolon_opt nested_name_specifier template_opt template_id_name
            //
            case 279: { action.   consumeQualifiedId(true);             break;
            }  
  
            //
            // Rule 281:  elaborated_type_specifier ::= class_keyword dcolon_opt nested_name_specifier_opt identifier_name
            //
            case 281: { action.   consumeTypeSpecifierElaborated(false);             break;
            }  
  
            //
            // Rule 282:  elaborated_type_specifier ::= class_keyword dcolon_opt nested_name_specifier_opt template_opt template_id_name
            //
            case 282: { action.   consumeTypeSpecifierElaborated(true);              break;
            }  
  
            //
            // Rule 283:  elaborated_type_specifier ::= enum dcolon_opt nested_name_specifier_opt identifier_name
            //
            case 283: { action.   consumeTypeSpecifierElaborated(false);             break;
            }  
  
            //
            // Rule 284:  enum_specifier ::= enum { <openscope-ast> enumerator_list_opt }
            //
            case 284: { action.   consumeTypeSpecifierEnumeration(false);            break;
            }  
  
            //
            // Rule 285:  enum_specifier ::= enum identifier_token { <openscope-ast> enumerator_list_opt }
            //
            case 285: { action.   consumeTypeSpecifierEnumeration(true);            break;
            }  
  
            //
            // Rule 290:  enumerator_definition ::= identifier_token
            //
            case 290: { action.   consumeEnumerator(false);            break;
            }  
  
            //
            // Rule 291:  enumerator_definition ::= identifier_token = constant_expression
            //
            case 291: { action.   consumeEnumerator(true);            break;
            }  
  
            //
            // Rule 295:  named_namespace_definition ::= namespace namespace_name { <openscope-ast> declaration_seq_opt }
            //
            case 295: { action.   consumeNamespaceDefinition(true);             break;
            }  
  
            //
            // Rule 296:  unnamed_namespace_definition ::= namespace { <openscope-ast> declaration_seq_opt }
            //
            case 296: { action.   consumeNamespaceDefinition(false);             break;
            }  
  
            //
            // Rule 297:  namespace_alias_definition ::= namespace identifier_token = dcolon_opt nested_name_specifier_opt namespace_name ;
            //
            case 297: { action.   consumeNamespaceAliasDefinition();            break;
            }  
  
            //
            // Rule 298:  using_declaration ::= using typename_opt dcolon_opt nested_name_specifier_opt unqualified_id_name ;
            //
            case 298: { action.   consumeUsingDeclaration();             break;
            }  
  
            //
            // Rule 299:  typename_opt ::= typename
            //
            case 299: { action.   consumePlaceHolder();             break;
            }  
  
            //
            // Rule 300:  typename_opt ::= $Empty
            //
            case 300: { action.   consumeEmpty();             break;
            }  
  
            //
            // Rule 301:  using_directive ::= using namespace dcolon_opt nested_name_specifier_opt namespace_name ;
            //
            case 301: { action.   consumeUsingDirective();             break;
            }  
  
            //
            // Rule 302:  asm_definition ::= asm ( stringlit ) ;
            //
            case 302: { action.   consumeDeclarationASM();            break;
            }  
  
            //
            // Rule 303:  linkage_specification ::= extern stringlit { <openscope-ast> declaration_seq_opt }
            //
            case 303: { action.   consumeLinkageSpecification();             break;
            }  
  
            //
            // Rule 304:  linkage_specification ::= extern stringlit <openscope-ast> declaration
            //
            case 304: { action.   consumeLinkageSpecification();             break;
            }  
  
            //
            // Rule 309:  init_declarator_complete ::= init_declarator
            //
            case 309: { action.   consumeInitDeclaratorComplete();             break;
            }  
  
            //
            // Rule 311:  init_declarator ::= declarator initializer
            //
            case 311: { action.   consumeDeclaratorWithInitializer(true);             break;
            }  
  
            //
            // Rule 313:  declarator ::= <openscope-ast> ptr_operator_seq direct_declarator
            //
            case 313: { action.   consumeDeclaratorWithPointer(true);             break;
            }  
  
            //
            // Rule 315:  function_declarator ::= <openscope-ast> ptr_operator_seq direct_declarator
            //
            case 315: { action.   consumeDeclaratorWithPointer(true);             break;
            }  
  
            //
            // Rule 319:  basic_direct_declarator ::= declarator_id_name
            //
            case 319: { action.   consumeDirectDeclaratorIdentifier();             break;
            }  
  
            //
            // Rule 320:  basic_direct_declarator ::= ( declarator )
            //
            case 320: { action.   consumeDirectDeclaratorBracketed();             break;
            }  
  
            //
            // Rule 321:  function_direct_declarator ::= basic_direct_declarator ( <openscope-ast> parameter_declaration_clause ) <openscope-ast> cv_qualifier_seq_opt <openscope-ast> exception_specification_opt
            //
            case 321: { action.   consumeDirectDeclaratorFunctionDeclarator(true);             break;
            }  
  
            //
            // Rule 322:  array_direct_declarator ::= array_direct_declarator array_modifier
            //
            case 322: { action.   consumeDirectDeclaratorArrayDeclarator(true);             break;
            }  
  
            //
            // Rule 323:  array_direct_declarator ::= basic_direct_declarator array_modifier
            //
            case 323: { action.   consumeDirectDeclaratorArrayDeclarator(true);             break;
            }  
  
            //
            // Rule 324:  array_modifier ::= [ constant_expression ]
            //
            case 324: { action.   consumeDirectDeclaratorArrayModifier(true);             break;
            }  
  
            //
            // Rule 325:  array_modifier ::= [ ]
            //
            case 325: { action.   consumeDirectDeclaratorArrayModifier(false);             break;
            }  
  
            //
            // Rule 326:  ptr_operator ::= * <openscope-ast> cv_qualifier_seq_opt
            //
            case 326: { action.   consumePointer();             break;
            }  
  
            //
            // Rule 327:  ptr_operator ::= &
            //
            case 327: { action.   consumeReferenceOperator();             break;
            }  
  
            //
            // Rule 328:  ptr_operator ::= dcolon_opt nested_name_specifier * <openscope-ast> cv_qualifier_seq_opt
            //
            case 328: { action.   consumePointerToMember();             break;
            }  
  
            //
            // Rule 334:  cv_qualifier ::= const
            //
            case 334: { action.   consumeDeclSpecToken();            break;
            }  
  
            //
            // Rule 335:  cv_qualifier ::= volatile
            //
            case 335: { action.   consumeDeclSpecToken();            break;
            }  
  
            //
            // Rule 337:  declarator_id_name ::= dcolon_opt nested_name_specifier_opt type_name
            //
            case 337: { action.   consumeQualifiedId(false);             break;
            }  
  
            //
            // Rule 338:  type_id ::= type_specifier_seq
            //
            case 338: { action.   consumeTypeId(false);             break;
            }  
  
            //
            // Rule 339:  type_id ::= type_specifier_seq abstract_declarator
            //
            case 339: { action.   consumeTypeId(true);             break;
            }  
  
            //
            // Rule 342:  abstract_declarator ::= <openscope-ast> ptr_operator_seq
            //
            case 342: { action.   consumeDeclaratorWithPointer(false);             break;
            }  
  
            //
            // Rule 343:  abstract_declarator ::= <openscope-ast> ptr_operator_seq direct_abstract_declarator
            //
            case 343: { action.   consumeDeclaratorWithPointer(true);             break;
            }  
  
            //
            // Rule 347:  basic_direct_abstract_declarator ::= ( abstract_declarator )
            //
            case 347: { action.   consumeDirectDeclaratorBracketed();             break;
            }  
  
            //
            // Rule 348:  basic_direct_abstract_declarator ::= ( )
            //
            case 348: { action.   consumeAbstractDeclaratorEmpty();             break;
            }  
  
            //
            // Rule 349:  array_direct_abstract_declarator ::= array_modifier
            //
            case 349: { action.   consumeDirectDeclaratorArrayDeclarator(false);             break;
            }  
  
            //
            // Rule 350:  array_direct_abstract_declarator ::= array_direct_abstract_declarator array_modifier
            //
            case 350: { action.   consumeDirectDeclaratorArrayDeclarator(true);             break;
            }  
  
            //
            // Rule 351:  array_direct_abstract_declarator ::= basic_direct_abstract_declarator array_modifier
            //
            case 351: { action.   consumeDirectDeclaratorArrayDeclarator(true);             break;
            }  
  
            //
            // Rule 352:  function_direct_abstract_declarator ::= basic_direct_abstract_declarator ( <openscope-ast> parameter_declaration_clause ) <openscope-ast> cv_qualifier_seq_opt <openscope-ast> exception_specification_opt
            //
            case 352: { action.   consumeDirectDeclaratorFunctionDeclarator(true);             break;
            }  
  
            //
            // Rule 353:  function_direct_abstract_declarator ::= ( <openscope-ast> parameter_declaration_clause ) <openscope-ast> cv_qualifier_seq_opt <openscope-ast> exception_specification_opt
            //
            case 353: { action.   consumeDirectDeclaratorFunctionDeclarator(false);             break;
            }  
  
            //
            // Rule 354:  parameter_declaration_clause ::= parameter_declaration_list_opt ...
            //
            case 354: { action.   consumePlaceHolder();             break;
            }  
  
            //
            // Rule 355:  parameter_declaration_clause ::= parameter_declaration_list_opt
            //
            case 355: { action.   consumeEmpty();             break;
            }  
  
            //
            // Rule 356:  parameter_declaration_clause ::= parameter_declaration_list , ...
            //
            case 356: { action.   consumePlaceHolder();             break;
            }  
  
            //
            // Rule 362:  abstract_declarator_opt ::= $Empty
            //
            case 362: { action.   consumeEmpty();             break;
            }  
  
            //
            // Rule 363:  parameter_declaration ::= declaration_specifiers parameter_init_declarator
            //
            case 363: { action.   consumeParameterDeclaration();             break;
            }  
  
            //
            // Rule 364:  parameter_declaration ::= declaration_specifiers
            //
            case 364: { action.   consumeParameterDeclarationWithoutDeclarator();             break;
            }  
  
            //
            // Rule 366:  parameter_init_declarator ::= declarator = parameter_initializer
            //
            case 366: { action.   consumeDeclaratorWithInitializer(true);             break;
            }  
  
            //
            // Rule 368:  parameter_init_declarator ::= abstract_declarator = parameter_initializer
            //
            case 368: { action.   consumeDeclaratorWithInitializer(true);             break;
            }  
  
            //
            // Rule 369:  parameter_init_declarator ::= = parameter_initializer
            //
            case 369: { action.   consumeDeclaratorWithInitializer(false);             break;
            }  
  
            //
            // Rule 370:  parameter_initializer ::= assignment_expression
            //
            case 370: { action.   consumeInitializer();             break;
            }  
  
            //
            // Rule 371:  function_definition ::= declaration_specifiers_opt function_declarator <openscope-ast> ctor_initializer_list_opt function_body
            //
            case 371: { action.   consumeFunctionDefinition(false);             break;
            }  
  
            //
            // Rule 372:  function_definition ::= declaration_specifiers_opt function_declarator try <openscope-ast> ctor_initializer_list_opt function_body <openscope-ast> handler_seq
            //
            case 372: { action.   consumeFunctionDefinition(true);             break;
            }  
  
            //
            // Rule 375:  initializer ::= ( expression_list )
            //
            case 375: { action.   consumeInitializerConstructor();             break;
            }  
  
            //
            // Rule 376:  initializer_clause ::= assignment_expression
            //
            case 376: { action.   consumeInitializer();             break;
            }  
  
            //
            // Rule 377:  initializer_clause ::= start_initializer_list { <openscope-ast> initializer_list , } end_initializer_list
            //
            case 377: { action.   consumeInitializerList();             break;
            }  
  
            //
            // Rule 378:  initializer_clause ::= start_initializer_list { <openscope-ast> initializer_list } end_initializer_list
            //
            case 378: { action.   consumeInitializerList();             break;
            }  
  
            //
            // Rule 379:  initializer_clause ::= { <openscope-ast> }
            //
            case 379: { action.   consumeInitializerList();             break;
            }  
  
            //
            // Rule 380:  start_initializer_list ::= $Empty
            //
            case 380: { action.   initializerListStart();            break;
            }  
  
            //
            // Rule 381:  end_initializer_list ::= $Empty
            //
            case 381: { action.   initializerListEnd();            break;
            }  
  
            //
            // Rule 386:  class_specifier ::= class_head { <openscope-ast> member_declaration_list_opt }
            //
            case 386: { action.   consumeClassSpecifier();             break;
            }  
  
            //
            // Rule 387:  class_head ::= class_keyword identifier_name_opt <openscope-ast> base_clause_opt
            //
            case 387: { action.   consumeClassHead(false);             break;
            }  
  
            //
            // Rule 388:  class_head ::= class_keyword template_id_name <openscope-ast> base_clause_opt
            //
            case 388: { action.   consumeClassHead(false);             break;
            }  
  
            //
            // Rule 389:  class_head ::= class_keyword nested_name_specifier identifier_name <openscope-ast> base_clause_opt
            //
            case 389: { action.   consumeClassHead(true);             break;
            }  
  
            //
            // Rule 390:  class_head ::= class_keyword nested_name_specifier template_id_name <openscope-ast> base_clause_opt
            //
            case 390: { action.   consumeClassHead(true);             break;
            }  
  
            //
            // Rule 392:  identifier_name_opt ::= $Empty
            //
            case 392: { action.   consumeEmpty();             break;
            } 
  
            //
            // Rule 396:  visibility_label ::= access_specifier_keyword :
            //
            case 396: { action.   consumeVisibilityLabel();             break;
            }  
  
            //
            // Rule 397:  member_declaration ::= declaration_specifiers_opt <openscope-ast> member_declarator_list ;
            //
            case 397: { action.   consumeDeclarationSimple(true);             break;
            }  
  
            //
            // Rule 398:  member_declaration ::= declaration_specifiers_opt ;
            //
            case 398: { action.   consumeDeclarationSimple(false);             break;
            }  
  
            //
            // Rule 401:  member_declaration ::= dcolon_opt nested_name_specifier template_opt unqualified_id_name ;
            //
            case 401: { action.   consumeMemberDeclarationQualifiedId();             break;
            }  
  
            //
            // Rule 407:  member_declaration ::= ERROR_TOKEN
            //
            case 407: { action.   consumeDeclarationProblem();             break;
            }  
  
            //
            // Rule 415:  member_declarator ::= declarator constant_initializer
            //
            case 415: { action.   consumeMemberDeclaratorWithInitializer();             break;
            }  
  
            //
            // Rule 416:  member_declarator ::= bit_field_declarator : constant_expression
            //
            case 416: { action.   consumeBitField(true);             break;
            }  
  
            //
            // Rule 417:  member_declarator ::= : constant_expression
            //
            case 417: { action.   consumeBitField(false);             break;
            }  
  
            //
            // Rule 418:  bit_field_declarator ::= identifier_name
            //
            case 418: { action.   consumeDirectDeclaratorIdentifier();             break;
            }  
  
            //
            // Rule 419:  constant_initializer ::= = constant_expression
            //
            case 419: { action.   consumeInitializer();             break;
            }  
  
            //
            // Rule 425:  base_specifier ::= dcolon_opt nested_name_specifier_opt class_name
            //
            case 425: { action.   consumeBaseSpecifier(false, false);             break;
            }  
  
            //
            // Rule 426:  base_specifier ::= virtual access_specifier_keyword_opt dcolon_opt nested_name_specifier_opt class_name
            //
            case 426: { action.   consumeBaseSpecifier(true, true);             break;
            }  
  
            //
            // Rule 427:  base_specifier ::= access_specifier_keyword virtual dcolon_opt nested_name_specifier_opt class_name
            //
            case 427: { action.   consumeBaseSpecifier(true, true);             break;
            }  
  
            //
            // Rule 428:  base_specifier ::= access_specifier_keyword dcolon_opt nested_name_specifier_opt class_name
            //
            case 428: { action.   consumeBaseSpecifier(true, false);             break;
            }  
  
            //
            // Rule 429:  access_specifier_keyword ::= private
            //
            case 429: { action.   consumeToken();             break;
            }  
  
            //
            // Rule 430:  access_specifier_keyword ::= protected
            //
            case 430: { action.   consumeToken();             break;
            }  
  
            //
            // Rule 431:  access_specifier_keyword ::= public
            //
            case 431: { action.   consumeToken();             break;
            }  
  
            //
            // Rule 433:  access_specifier_keyword_opt ::= $Empty
            //
            case 433: { action.   consumeEmpty();             break;
            }  
  
            //
            // Rule 435:  conversion_function_id_name ::= conversion_function_id < <openscope-ast> template_argument_list_opt >
            //
            case 435: { action.   consumeTemplateId();             break;
            }  
  
            //
            // Rule 436:  conversion_function_id ::= operator conversion_type_id
            //
            case 436: { action.   consumeConversionName();            break;
            }  
  
            //
            // Rule 437:  conversion_type_id ::= type_specifier_seq conversion_declarator
            //
            case 437: { action.   consumeTypeId(true);             break;
            }  
  
            //
            // Rule 438:  conversion_type_id ::= type_specifier_seq
            //
            case 438: { action.   consumeTypeId(false);             break;
            }  
  
            //
            // Rule 439:  conversion_declarator ::= <openscope-ast> ptr_operator_seq
            //
            case 439: { action.   consumeDeclaratorWithPointer(false);             break;
            }  
  
            //
            // Rule 445:  mem_initializer ::= mem_initializer_name ( expression_list_opt )
            //
            case 445: { action.   consumeConstructorChainInitializer();             break;
            }  
  
            //
            // Rule 446:  mem_initializer_name ::= dcolon_opt nested_name_specifier_opt class_name
            //
            case 446: { action.   consumeQualifiedId(false);             break;
            }  
  
            //
            // Rule 449:  operator_function_id_name ::= operator_id_name < <openscope-ast> template_argument_list_opt >
            //
            case 449: { action.   consumeTemplateId();             break;
            }  
  
            //
            // Rule 450:  operator_id_name ::= operator overloadable_operator
            //
            case 450: { action.   consumeOperatorName();             break;
            }  
  
            //
            // Rule 493:  template_declaration ::= export_opt template < <openscope-ast> template_parameter_list > declaration
            //
            case 493: { action.   consumeTemplateDeclaration();             break;
            }  
  
            //
            // Rule 494:  export_opt ::= export
            //
            case 494: { action.   consumePlaceHolder();             break;
            }  
  
            //
            // Rule 495:  export_opt ::= $Empty
            //
            case 495: { action.   consumeEmpty();             break;
            }  
  
            //
            // Rule 499:  template_parameter ::= parameter_declaration
            //
            case 499: { action.   consumeTemplateParamterDeclaration();             break;
            }  
  
            //
            // Rule 500:  type_parameter ::= class identifier_name_opt
            //
            case 500: { action.   consumeSimpleTypeTemplateParameter(false);             break;
            }  
  
            //
            // Rule 501:  type_parameter ::= class identifier_name_opt = type_id
            //
            case 501: { action.   consumeSimpleTypeTemplateParameter(true);             break;
            }  
  
            //
            // Rule 502:  type_parameter ::= typename identifier_name_opt
            //
            case 502: { action.   consumeSimpleTypeTemplateParameter(false);             break;
            }  
  
            //
            // Rule 503:  type_parameter ::= typename identifier_name_opt = type_id
            //
            case 503: { action.   consumeSimpleTypeTemplateParameter(true);             break;
            }  
  
            //
            // Rule 504:  type_parameter ::= template < <openscope-ast> template_parameter_list > class identifier_name_opt
            //
            case 504: { action.   consumeTemplatedTypeTemplateParameter(false);             break;
            }  
  
            //
            // Rule 505:  type_parameter ::= template < <openscope-ast> template_parameter_list > class identifier_name_opt = id_expression
            //
            case 505: { action.   consumeTemplatedTypeTemplateParameter(true);             break;
            }  
  
            //
            // Rule 506:  template_id_name ::= identifier_name < <openscope-ast> template_argument_list_opt >
            //
            case 506: { action.   consumeTemplateId();             break;
            }  
  
            //
            // Rule 511:  template_argument ::= assignment_expression
            //
            case 511: { action.   consumeTemplateArgumentExpression();             break;
            }  
  
            //
            // Rule 512:  template_argument ::= type_id
            //
            case 512: { action.   consumeTemplateArgumentTypeId();             break;
            }  
  
            //
            // Rule 513:  explicit_instantiation ::= template declaration
            //
            case 513: { action.   consumeTemplateExplicitInstantiation();             break;
            }  
  
            //
            // Rule 514:  explicit_specialization ::= template < > declaration
            //
            case 514: { action.   consumeTemplateExplicitSpecialization();             break;
            }  
  
            //
            // Rule 515:  try_block ::= try compound_statement <openscope-ast> handler_seq
            //
            case 515: { action.   consumeStatementTryBlock();             break;
            }  
  
            //
            // Rule 518:  handler ::= catch ( exception_declaration ) compound_statement
            //
            case 518: { action.   consumeStatementCatchHandler(false);             break;
            }  
  
            //
            // Rule 519:  handler ::= catch ( ... ) compound_statement
            //
            case 519: { action.   consumeStatementCatchHandler(true);             break;
            }  
  
            //
            // Rule 520:  exception_declaration ::= type_specifier_seq <openscope-ast> declarator
            //
            case 520: { action.   consumeDeclarationSimple(true);             break;
            }  
  
            //
            // Rule 521:  exception_declaration ::= type_specifier_seq <openscope-ast> abstract_declarator
            //
            case 521: { action.   consumeDeclarationSimple(true);             break;
            }  
  
            //
            // Rule 522:  exception_declaration ::= type_specifier_seq
            //
            case 522: { action.   consumeDeclarationSimple(false);             break;
            }  
  
            //
            // Rule 524:  exception_specification ::= throw ( )
            //
            case 524: { action.   consumePlaceHolder();             break;
            }  
  
            //
            // Rule 530:  type_parameter_start ::= ERROR_TOKEN
            //
            case 530: { action.   consumeDeclarationProblem();             break;
            }  

    
            default:
                break;
        }
        return;
    }
}

