/**
 * ******************************************************************************
 * Copyright (c) 2016, 2017 Kichwa Coders Ltd (https://kichwacoders.com/) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *  ******************************************************************************
 * 
 * 
 * generated by Xtext 2.10.0
 * Copyright header generated by GenerateLinkerScript.mwe2
 */
package org.eclipse.cdt.linkerscript.linkerScript;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.eclipse.cdt.linkerscript.linkerScript.LinkerScriptPackage
 * @generated
 */
public interface LinkerScriptFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LinkerScriptFactory eINSTANCE = org.eclipse.cdt.linkerscript.linkerScript.impl.LinkerScriptFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Linker Script</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Linker Script</em>'.
   * @generated
   */
  LinkerScript createLinkerScript();

  /**
   * Returns a new object of class '<em>Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement</em>'.
   * @generated
   */
  LinkerScriptStatement createLinkerScriptStatement();

  /**
   * Returns a new object of class '<em>Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement</em>'.
   * @generated
   */
  Statement createStatement();

  /**
   * Returns a new object of class '<em>File List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>File List</em>'.
   * @generated
   */
  FileList createFileList();

  /**
   * Returns a new object of class '<em>File List Name</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>File List Name</em>'.
   * @generated
   */
  FileListName createFileListName();

  /**
   * Returns a new object of class '<em>Phdrs Command</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Phdrs Command</em>'.
   * @generated
   */
  PhdrsCommand createPhdrsCommand();

  /**
   * Returns a new object of class '<em>Phdr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Phdr</em>'.
   * @generated
   */
  Phdr createPhdr();

  /**
   * Returns a new object of class '<em>Sections Command</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sections Command</em>'.
   * @generated
   */
  SectionsCommand createSectionsCommand();

  /**
   * Returns a new object of class '<em>Output Section Command</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Output Section Command</em>'.
   * @generated
   */
  OutputSectionCommand createOutputSectionCommand();

  /**
   * Returns a new object of class '<em>Output Section</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Output Section</em>'.
   * @generated
   */
  OutputSection createOutputSection();

  /**
   * Returns a new object of class '<em>Output Section Align</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Output Section Align</em>'.
   * @generated
   */
  OutputSectionAlign createOutputSectionAlign();

  /**
   * Returns a new object of class '<em>Output Section Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Output Section Constraint</em>'.
   * @generated
   */
  OutputSectionConstraint createOutputSectionConstraint();

  /**
   * Returns a new object of class '<em>Output Section Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Output Section Type</em>'.
   * @generated
   */
  OutputSectionType createOutputSectionType();

  /**
   * Returns a new object of class '<em>Assignment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Assignment</em>'.
   * @generated
   */
  Assignment createAssignment();

  /**
   * Returns a new object of class '<em>Input Section</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Input Section</em>'.
   * @generated
   */
  InputSection createInputSection();

  /**
   * Returns a new object of class '<em>Wildcard</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Wildcard</em>'.
   * @generated
   */
  Wildcard createWildcard();

  /**
   * Returns a new object of class '<em>Memory Command</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Memory Command</em>'.
   * @generated
   */
  MemoryCommand createMemoryCommand();

  /**
   * Returns a new object of class '<em>Memory</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Memory</em>'.
   * @generated
   */
  Memory createMemory();

  /**
   * Returns a new object of class '<em>LExpression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>LExpression</em>'.
   * @generated
   */
  LExpression createLExpression();

  /**
   * Returns a new object of class '<em>Statement Assignment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement Assignment</em>'.
   * @generated
   */
  StatementAssignment createStatementAssignment();

  /**
   * Returns a new object of class '<em>Statement Startup</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement Startup</em>'.
   * @generated
   */
  StatementStartup createStatementStartup();

  /**
   * Returns a new object of class '<em>Statement Entry</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement Entry</em>'.
   * @generated
   */
  StatementEntry createStatementEntry();

  /**
   * Returns a new object of class '<em>Statement Assert</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement Assert</em>'.
   * @generated
   */
  StatementAssert createStatementAssert();

  /**
   * Returns a new object of class '<em>Statement Target</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement Target</em>'.
   * @generated
   */
  StatementTarget createStatementTarget();

  /**
   * Returns a new object of class '<em>Statement Search Dir</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement Search Dir</em>'.
   * @generated
   */
  StatementSearchDir createStatementSearchDir();

  /**
   * Returns a new object of class '<em>Statement Output</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement Output</em>'.
   * @generated
   */
  StatementOutput createStatementOutput();

  /**
   * Returns a new object of class '<em>Statement Output Format</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement Output Format</em>'.
   * @generated
   */
  StatementOutputFormat createStatementOutputFormat();

  /**
   * Returns a new object of class '<em>Statement Output Arch</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement Output Arch</em>'.
   * @generated
   */
  StatementOutputArch createStatementOutputArch();

  /**
   * Returns a new object of class '<em>Statement Force Common Allocation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement Force Common Allocation</em>'.
   * @generated
   */
  StatementForceCommonAllocation createStatementForceCommonAllocation();

  /**
   * Returns a new object of class '<em>Statement Inhibit Common Allocation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement Inhibit Common Allocation</em>'.
   * @generated
   */
  StatementInhibitCommonAllocation createStatementInhibitCommonAllocation();

  /**
   * Returns a new object of class '<em>Statement Input</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement Input</em>'.
   * @generated
   */
  StatementInput createStatementInput();

  /**
   * Returns a new object of class '<em>Statement Group</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement Group</em>'.
   * @generated
   */
  StatementGroup createStatementGroup();

  /**
   * Returns a new object of class '<em>Statement Map</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement Map</em>'.
   * @generated
   */
  StatementMap createStatementMap();

  /**
   * Returns a new object of class '<em>Statement No Cross Refs</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement No Cross Refs</em>'.
   * @generated
   */
  StatementNoCrossRefs createStatementNoCrossRefs();

  /**
   * Returns a new object of class '<em>Statement No Cross Refs To</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement No Cross Refs To</em>'.
   * @generated
   */
  StatementNoCrossRefsTo createStatementNoCrossRefsTo();

  /**
   * Returns a new object of class '<em>Statement Extern</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement Extern</em>'.
   * @generated
   */
  StatementExtern createStatementExtern();

  /**
   * Returns a new object of class '<em>Statement Include</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement Include</em>'.
   * @generated
   */
  StatementInclude createStatementInclude();

  /**
   * Returns a new object of class '<em>Statement Nop</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement Nop</em>'.
   * @generated
   */
  StatementNop createStatementNop();

  /**
   * Returns a new object of class '<em>Output Section Align Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Output Section Align Expression</em>'.
   * @generated
   */
  OutputSectionAlignExpression createOutputSectionAlignExpression();

  /**
   * Returns a new object of class '<em>Output Section Align With Input</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Output Section Align With Input</em>'.
   * @generated
   */
  OutputSectionAlignWithInput createOutputSectionAlignWithInput();

  /**
   * Returns a new object of class '<em>Output Section Constraint Only If RO</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Output Section Constraint Only If RO</em>'.
   * @generated
   */
  OutputSectionConstraintOnlyIfRO createOutputSectionConstraintOnlyIfRO();

  /**
   * Returns a new object of class '<em>Output Section Constraint Only If RW</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Output Section Constraint Only If RW</em>'.
   * @generated
   */
  OutputSectionConstraintOnlyIfRW createOutputSectionConstraintOnlyIfRW();

  /**
   * Returns a new object of class '<em>Output Section Constraint Special</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Output Section Constraint Special</em>'.
   * @generated
   */
  OutputSectionConstraintSpecial createOutputSectionConstraintSpecial();

  /**
   * Returns a new object of class '<em>Output Section Type No Load</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Output Section Type No Load</em>'.
   * @generated
   */
  OutputSectionTypeNoLoad createOutputSectionTypeNoLoad();

  /**
   * Returns a new object of class '<em>Output Section Type DSect</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Output Section Type DSect</em>'.
   * @generated
   */
  OutputSectionTypeDSect createOutputSectionTypeDSect();

  /**
   * Returns a new object of class '<em>Output Section Type Copy</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Output Section Type Copy</em>'.
   * @generated
   */
  OutputSectionTypeCopy createOutputSectionTypeCopy();

  /**
   * Returns a new object of class '<em>Output Section Type Info</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Output Section Type Info</em>'.
   * @generated
   */
  OutputSectionTypeInfo createOutputSectionTypeInfo();

  /**
   * Returns a new object of class '<em>Output Section Type Overlay</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Output Section Type Overlay</em>'.
   * @generated
   */
  OutputSectionTypeOverlay createOutputSectionTypeOverlay();

  /**
   * Returns a new object of class '<em>Statement Create Object Symbols</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement Create Object Symbols</em>'.
   * @generated
   */
  StatementCreateObjectSymbols createStatementCreateObjectSymbols();

  /**
   * Returns a new object of class '<em>Statement Constructors</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement Constructors</em>'.
   * @generated
   */
  StatementConstructors createStatementConstructors();

  /**
   * Returns a new object of class '<em>Statement Constructors Sorted</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement Constructors Sorted</em>'.
   * @generated
   */
  StatementConstructorsSorted createStatementConstructorsSorted();

  /**
   * Returns a new object of class '<em>Statement Data</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement Data</em>'.
   * @generated
   */
  StatementData createStatementData();

  /**
   * Returns a new object of class '<em>Statement Fill</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement Fill</em>'.
   * @generated
   */
  StatementFill createStatementFill();

  /**
   * Returns a new object of class '<em>Statement Input Section</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement Input Section</em>'.
   * @generated
   */
  StatementInputSection createStatementInputSection();

  /**
   * Returns a new object of class '<em>Assignment Hidden</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Assignment Hidden</em>'.
   * @generated
   */
  AssignmentHidden createAssignmentHidden();

  /**
   * Returns a new object of class '<em>Assignment Provide</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Assignment Provide</em>'.
   * @generated
   */
  AssignmentProvide createAssignmentProvide();

  /**
   * Returns a new object of class '<em>Assignment Provide Hidden</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Assignment Provide Hidden</em>'.
   * @generated
   */
  AssignmentProvideHidden createAssignmentProvideHidden();

  /**
   * Returns a new object of class '<em>Input Section File</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Input Section File</em>'.
   * @generated
   */
  InputSectionFile createInputSectionFile();

  /**
   * Returns a new object of class '<em>Input Section Wild</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Input Section Wild</em>'.
   * @generated
   */
  InputSectionWild createInputSectionWild();

  /**
   * Returns a new object of class '<em>LTernary Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>LTernary Operation</em>'.
   * @generated
   */
  LTernaryOperation createLTernaryOperation();

  /**
   * Returns a new object of class '<em>LBinary Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>LBinary Operation</em>'.
   * @generated
   */
  LBinaryOperation createLBinaryOperation();

  /**
   * Returns a new object of class '<em>LUnary Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>LUnary Operation</em>'.
   * @generated
   */
  LUnaryOperation createLUnaryOperation();

  /**
   * Returns a new object of class '<em>LVariable</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>LVariable</em>'.
   * @generated
   */
  LVariable createLVariable();

  /**
   * Returns a new object of class '<em>LParenthesized Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>LParenthesized Expression</em>'.
   * @generated
   */
  LParenthesizedExpression createLParenthesizedExpression();

  /**
   * Returns a new object of class '<em>Length Call</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Length Call</em>'.
   * @generated
   */
  LengthCall createLengthCall();

  /**
   * Returns a new object of class '<em>Origin Call</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Origin Call</em>'.
   * @generated
   */
  OriginCall createOriginCall();

  /**
   * Returns a new object of class '<em>Align Call</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Align Call</em>'.
   * @generated
   */
  AlignCall createAlignCall();

  /**
   * Returns a new object of class '<em>Sizeof Call</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sizeof Call</em>'.
   * @generated
   */
  SizeofCall createSizeofCall();

  /**
   * Returns a new object of class '<em>At Call</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>At Call</em>'.
   * @generated
   */
  AtCall createAtCall();

  /**
   * Returns a new object of class '<em>LFeature Call</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>LFeature Call</em>'.
   * @generated
   */
  LFeatureCall createLFeatureCall();

  /**
   * Returns a new object of class '<em>LNumber Literal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>LNumber Literal</em>'.
   * @generated
   */
  LNumberLiteral createLNumberLiteral();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  LinkerScriptPackage getLinkerScriptPackage();

} //LinkerScriptFactory
