/**
 * ******************************************************************************
 * Copyright (c) 2016, 2017 Kichwa Coders Ltd (https://kichwacoders.com/) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *  ******************************************************************************
 * 
 * 
 * generated by Xtext 2.10.0
 * Copyright header generated by GenerateLinkerScript.mwe2
 */
package org.eclipse.cdt.linkerscript.linkerScript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement Output Format</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.cdt.linkerscript.linkerScript.StatementOutputFormat#getName <em>Name</em>}</li>
 *   <li>{@link org.eclipse.cdt.linkerscript.linkerScript.StatementOutputFormat#getBig <em>Big</em>}</li>
 *   <li>{@link org.eclipse.cdt.linkerscript.linkerScript.StatementOutputFormat#getLittle <em>Little</em>}</li>
 * </ul>
 *
 * @see org.eclipse.cdt.linkerscript.linkerScript.LinkerScriptPackage#getStatementOutputFormat()
 * @model
 * @generated
 */
public interface StatementOutputFormat extends Statement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.eclipse.cdt.linkerscript.linkerScript.LinkerScriptPackage#getStatementOutputFormat_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.eclipse.cdt.linkerscript.linkerScript.StatementOutputFormat#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Big</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Big</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Big</em>' attribute.
   * @see #setBig(String)
   * @see org.eclipse.cdt.linkerscript.linkerScript.LinkerScriptPackage#getStatementOutputFormat_Big()
   * @model
   * @generated
   */
  String getBig();

  /**
   * Sets the value of the '{@link org.eclipse.cdt.linkerscript.linkerScript.StatementOutputFormat#getBig <em>Big</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Big</em>' attribute.
   * @see #getBig()
   * @generated
   */
  void setBig(String value);

  /**
   * Returns the value of the '<em><b>Little</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Little</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Little</em>' attribute.
   * @see #setLittle(String)
   * @see org.eclipse.cdt.linkerscript.linkerScript.LinkerScriptPackage#getStatementOutputFormat_Little()
   * @model
   * @generated
   */
  String getLittle();

  /**
   * Sets the value of the '{@link org.eclipse.cdt.linkerscript.linkerScript.StatementOutputFormat#getLittle <em>Little</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Little</em>' attribute.
   * @see #getLittle()
   * @generated
   */
  void setLittle(String value);

} // StatementOutputFormat
