/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.cdt.linkerscript.linkerScript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement Inhibit Common Allocation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.eclipse.cdt.linkerscript.linkerScript.LinkerScriptPackage#getStatementInhibitCommonAllocation()
 * @model
 * @generated
 */
public interface StatementInhibitCommonAllocation extends Statement
{
} // StatementInhibitCommonAllocation
