/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.cdt.linkerscript.linkerScript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Wildcard Sort None</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.eclipse.cdt.linkerscript.linkerScript.LinkerScriptPackage#getWildcardSortNone()
 * @model
 * @generated
 */
public interface WildcardSortNone extends Wildcard
{
} // WildcardSortNone
