////
Copyright (c) 2000, 2025 Contributors to the Eclipse Foundation
This program and the accompanying materials
are made available under the terms of the Eclipse Public License 2.0
which accompanies this distribution, and is available at
https://www.eclipse.org/legal/epl-2.0/

SPDX-License-Identifier: EPL-2.0
////

// pull in shared headers, footers, etc
:docinfo: shared

// support image rendering and table of contents within GitHub
ifdef::env-github[]
:imagesdir: ../../images
:toc:
:toc-placement!:
endif::[]

// enable support for button, menu and keyboard macros
:experimental:

// Until ENDOFHEADER the content must match adoc-headers.txt for consistency,
// this is checked by the build in do_generate_asciidoc.sh, which also ensures
// that the checked in html is up to date.
// do_generate_asciidoc.sh can also be used to apply this header to all the
// adoc files.
// ENDOFHEADER

== General information

The LLVM with Clang/GCC for Eclipse CDT plug-in integrates an LLVM toolchain using
the Clang or llvm-gcc compiler with the CDT managed build system to compile C/(cpp} programs.

http://www.llvm.org[LLVM] is a modern toolchain that supports the
compilation of C/(cpp} code (among others) to LLVM virtual machine's
_bitcode_, which in turn can be compiled to each platform's native
binary.

The plug-in integrates the following tools from the LLVM toolchain:
Clang/Clang{plus}{plus}/llvm-gcc/llvm-g{plus}{plus} (C/(cpp} compilers), llvm-ld (linker),
llvm-ar (archiver), llvm-as (assembler), llc (static compiler) and lli
(JIT/Interpreter).
