////
Copyright (c) 2000, 2025 Contributors to the Eclipse Foundation
This program and the accompanying materials
are made available under the terms of the Eclipse Public License 2.0
which accompanies this distribution, and is available at
https://www.eclipse.org/legal/epl-2.0/

SPDX-License-Identifier: EPL-2.0
////

// pull in shared headers, footers, etc
:docinfo: shared

// support image rendering and table of contents within GitHub
ifdef::env-github[]
:imagesdir: ../../images
:toc:
:toc-placement!:
endif::[]

// enable support for button, menu and keyboard macros
:experimental:

// Until ENDOFHEADER the content must match adoc-headers.txt for consistency,
// this is checked by the build in do_generate_asciidoc.sh, which also ensures
// that the checked in html is up to date.
// do_generate_asciidoc.sh can also be used to apply this header to all the
// adoc files.
// ENDOFHEADER

== Initial configuration

On Linux and macOS hosts, the LLVM toolchain will typically be installed via the package
management tool provided by the Linux distribution or as part of the
_Xcode Command Line Tools_ and will be located on the system `PATH`.
If your LLVM toolchain is not on the system `PATH` when launching the Eclipse Workbench,
you may need to add the location of your LLVM binaries to the `PATH` environment variable
within Eclipse. This is done by navigating to Window -> Preferences ->
C/{cpp} -> Build -> Environment. Select the `PATH` environment variable and then edit its
value to point where your LLVM binaries are located.

If your `PATH` environment variable is set correctly, you should see the
_LLVM with Clang_ and _LLVM with GCC_ toolchains available for selection within the
CDT project wizard for managed build projects. The toolchains are available for both
C and {cpp} projects.

NOTE: Clang is automatically detected when installed on a Microsoft Windows host using
the MSYS2 package manager. It is not necessary to modify the `PATH`.
