/*******************************************************************************
 * Copyright (c) 2016, 2017 Kichwa Coders Ltd (https://kichwacoders.com/) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/

/*
 * generated by Xtext 2.10.0
 * Copyright header generated by GenerateLinkerScript.mwe2
 */
package org.eclipse.cdt.linkerscript.ui;

import com.google.inject.Injector;
import org.eclipse.cdt.linkerscript.ui.internal.LinkerscriptActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LinkerScriptExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LinkerscriptActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LinkerscriptActivator.getInstance().getInjector(LinkerscriptActivator.ORG_ECLIPSE_CDT_LINKERSCRIPT_LINKERSCRIPT);
	}
	
}
