/*******************************************************************************
 * Copyright (c) 2006 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/

package org.eclipse.cdt.errorparsers.xlc.tests;

import org.eclipse.cdt.errorparsers.xlc.XlcErrorParser;

import junit.framework.TestCase;


public class TestFloatingPoint extends TestCase {
	String err_msg;
	/**
	 * This function tests parseLine function of the
	 * XlcErrorParser class. Error message generated by
	 * xlc compiler with high severity (S) is given as 
	 * input for testing.  
	 */
	public void testparseLine()
	{
		XlcErrorParser aix = new XlcErrorParser();
		aix.parseLine(err_msg);
		assertEquals("temp9.c", aix.getFileName());
		assertEquals(11, aix.getLineNumber());
		assertEquals("S", aix.getSeverity());
		assertEquals(" Floating point constant 10.23.3 is not valid",
					aix.getMessage());
	}
	public TestFloatingPoint( String name)
	{
		super(name);
		err_msg = "\"temp9.c\", line 11.18: 1506-189 (S) " + 
		         "Floating point constant 10.23.3 is not valid";
	}
}