/*******************************************************************************
 * Copyright (c) 2006 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.cdt.errorparsers.xlc.tests;

import org.eclipse.cdt.errorparsers.xlc.XlcErrorParser;

import junit.framework.TestCase;

public class TestNoFuncProto extends TestCase {
	String err_msg;
	/**
	 * This function tests parseLine function of the
	 * XlcErrorParser class. Warning message generated by
	 * xlc compiler (W) is given as input for testing.  
	 */
	public void testparseLine()
	{
		XlcErrorParser aix = new XlcErrorParser();
		aix.parseLine(err_msg);
		assertEquals("temp1.c", aix.getFileName());
		assertEquals(5, aix.getLineNumber());
		assertEquals("W", aix.getSeverity());
		assertEquals(" No function prototype given for \"printf\".",aix.getMessage());
	}
	public TestNoFuncProto( String name)
	{
		super(name);
		err_msg = "\"temp1.c\", line 5.9: 1506-304 (W) "
					+ "No function prototype given for \"printf\".";
	}
}